### ISSUE TITLE
Factoring out constructor causes hang during Elaborate

### ISSUE THREAD

**Issue by vizziv** [urweb/urweb#1]
In the following excerpt from [this file](https://github.com/vizziv/UrLib/blob/76840052553e4fea14d7a8217cc4d954f9b6b7a1/userRequest.ur), I'd like to pass `submitRequests` as the constructor argument to `castL`, but doing so causes the compiler to hang during the Elaborate phase. The same thing happens if I try to substitute in just the `submitRequest` part. With the constructor expanded out as below, the relevant project (either `userRequest` or `test`) compiles successfully.

```urweb
type submitRequest h = {Submit : h.2 -> tunit, Request : h.1}
type submitRequests (hs :: {(Type * Type)}) = variant (map submitRequest hs)

fun signal (user : {Group : group, Member : member}) =
    (src : source (option (submitRequests handlers))) <- source None;
    listen user
           (@mapNm0 [fn _ h => (h.2 -> tunit) -> h.1 -> tunit] fl
                    (fn [others ::_] [nm ::_] [h] [[nm] ~ others]
                        _ (pf : equal _ _)
                        (submit : h.2 -> tunit) (req : h.1) =>
                        let
                            val cast =
                                castL pf
                                      (* Using [submitRequests] causes hang! *)
                                      [fn hs =>
                                          variant
                                              (map (fn h =>
                                                       {Submit : h.2 -> tunit,
                                                        Request : h.1})
                                                       hs)]
                        in
                            set src
                                (Some (cast (make [nm] {Submit = submit,
                                                        Request = req})))
                        end));
    return (Basis.signal src)
```

EDIT: Change link to point to relevant commit instead of latest (though the latest version exhibits the same issue).

**Comment by achlipala** [comment]
Ah, sorry, this was a good test run for the new GitHub work flow.  I didn't realize I needed to watch the repo, so I didn't see this issue until now.  Will look into it!

**Comment by vizziv** [comment]
I've run into a few other hangs, but they've all been from constraint problems that were conceivably not solvable, whereas this one seems like it should be easy.

**Comment by achlipala** [comment]
OK, it should be fixed now.  The latest contents of that repo compile for me, at least.  There were a few type-inference issues related to constructor-level tuples.
