### ISSUE TITLE
Add `-h` flag for showing help message

### ISSUE THREAD

**Issue by wisn** [urweb/urweb#100]
I think we need that flag to showing what `urweb` CLI could do. We may use `man urweb`, but personally it's better to provide information when someone run `urweb -h` or `urweb -help`.

When we run `urweb` command, we get the version information. I think instead of show version information, it's better to show help message.

Edit: After thinking a lot of more, I think it's no problem to showing Ur/Web version. But we still need that `-h` flag.

**Comment by wisn** [comment]
Sorry, duplicated with https://github.com/urweb/urweb/issues/63

**Comment by achlipala** [comment]
I think Ur/Web has already had this feature for a while.  Try running with `-h` and see!  (Maybe this is what you discovered by looking at that other issue.)

**Comment by wisn** [comment]
@achlipala I've installed Ur/Web on my Ubuntu machine and the `-h` still not working. Probably the package not updated?

**Comment by achlipala** [comment]
Yeah, or maybe it was added since the last Ur/Web release.

**Comment by wisn** [comment]
I will try to build from source then.
