### ISSUE TITLE
Add contributing guideline

### ISSUE THREAD

**Issue by wisn** [urweb/urweb#102]
Ur/Web is a very interesting project. It's better to add contributing guideline so we may contribute nicely.

**Comment by achlipala** [comment]
Not necessarily a bad idea, but I have no idea how to begin.

**Comment by wisn** [comment]
@achlipala How about something like [this](https://github.com/purescript/purescript/blob/master/CONTRIBUTING.md)?

Can you please check your email inbox? I've dropped something.

**Comment by achlipala** [comment]
Sorry, I'm very busy and expect to continue to be so for several months, at least.  It can take me weeks to respond to Ur/Web messages.

**Comment by wisn** [comment]
Okay

**Comment by achlipala** [comment]
No one responded on the mailing list when I asked whether contributor guidelines are worthwhile, so I'm going to err on the side of simplicity and leave them out for now.
