### ISSUE TITLE
Build issue: FreeBSD (Solved - use gmake.)

### ISSUE THREAD

**Issue by fullreset** [urweb/urweb#103]
I'm having trouble building on FreeBSD 11.0-STABLE (amd64.) This issue affects both the release archive (20170720) and clones of the current git repository. 

No matter what I try -- and I've tried many things -- I wind up with one of two results:

(1) **make** hangs after a series of libtool runs; and it always stalls at 

> `cat  | sed -e 's/$(SRC)\///g' > src/urweb.cm`

and for obvious reasons -- no inputs or args to `cat`. This happens out-of-the-box on the git clone. (I can confirm this behavior on OSX as well for the git clone, though the release compiles correctly.)

(2) The release bundle will compile the first time, but will only produce a 32-bit executable -- and that fails to run because there is no 32-bit version of libgmp on the system. With a second  `./configure; make`  on FreeBSD, issue (1) will also surface. (I haven't tried the second  `./configure; make`  on OSX because it worked -- "if it ain't broke", as they say -- but perhaps I should.)

Note: I am not an expert in -- nor a lover of -- **autoconf**. This might be part of the problem. :) But if anyone has any pointers it would be much appreciated.

Thanks.

FYI The FreeBSD ports collection _does_ include Ur/Web, but the version is too old for my needs ~ the build is from 2015.

**Comment by achlipala** [comment]
My first guess as to the problem: the `make` for that platform may not support the `$^` special variable, which on currently working platforms stands for the names of dependencies of the current rule.  Would you mind trying a small experiment to verify?  You should be able to find example fodder by searching for this variable in the Makefile you are building from.

**Comment by fullreset** [comment]
Ah! Thank you! That was exactly the problem. I confirmed it with a small test makefile, and using gmake instead of make results in a correct 64bit Ur/Web executable on FreeBSD11.0-Stable.

**Comment by achlipala** [comment]
OK, and should the `configure` script be changed to detect this problem?  Or were you not running it?

**Comment by fullreset** [comment]
I did run configure, so I guess it does need to be changed; but a simple note that `GNU make` is required in the `README.md` file would also suffice...

**Comment by achlipala** [comment]
I've extended the README with a note to that effect.  Thanks for the suggestion.
