### ISSUE TITLE
Multiple css classes using underscore throws error

### ISSUE THREAD

**Issue by nitinsurana** [urweb/urweb#104]
Hi
```
<button class={classes btn btn_sm btn_primary} value="Refresh"  onclick={fn _ => nl <- rpc(channelBuffers(r.Username)); set lss nl}></button>
```
Above code throws compilation error, but

```
<button class={classes btn btn_sm} value="Refresh"  onclick={fn _ => nl <- rpc(channelBuffers(r.Username)); set lss nl}></button>
```
and 
```
<button class={classes btn btn_primary} value="Refresh"  onclick={fn _ => nl <- rpc(channelBuffers(r.Username)); set lss nl}></button>
```
both compiles fine.

**Comment by achlipala** [comment]
`classes` takes exactly two arguments, so it makes sense that you'd get a type error from passing the wrong number of arguments.  I think you'll get the behavior you expect if you just put the value of the `class` attribute in double quotes (not curly braces) and follow normal HTML-style syntax.
