### ISSUE TITLE
Unable to use cssClass `table` from twitter-bootstrap

### ISSUE THREAD

**Issue by nitinsurana** [urweb/urweb#105]
Hi
Below doesn't compile because of the `table` class
```
<table border=1 class="table-bordered table-striped table-responsive table">
```
but 
```
<table border=1 class="table-bordered table-striped table-responsive ">
```
compiles fine.

I do have `style table` defined at the top of `.ur` file. I believe it's because it's taking `table` as some internal keyword ? Any fixes apart from fixing bootstrap.css itself.

**Comment by fullreset** [comment]
you can look at `bootstrap3.ur` & `bootstrap3.urp`; in the `ur` file you'll see that `table` is called `bs3_table` to avoid conflict w `table` as used in SQL code; and in the `urp` you'll see that the name gets rewritten to allow the use of vanilla (unmodified) bootstrap sources that expect the class to be called `table`.

**Comment by achlipala** [comment]
Good advice!  The issue has to do with `table`'s status as a keyword in Ur/Web, as you surmised.
