### ISSUE TITLE
Ur/JSON-RPC (or better yet: Ur/Platform = Ur/Web ++ Ur/JSON-RPC)

### ISSUE THREAD

**Issue by fullreset** [urweb/urweb#107]
Where in the sources might I begin if I wanted to created the new animal suggested in the subject? This allow websites to easily create APIs for 3rd-parties.

Or am I completely wrong, and an `rpc` type with suitable classes for `rpc` and `transaction rpc` are all that is needed? (That would be beautiful of course -- though the compiler would still need changes so that it would listen at different ports...)

PS This problem is solvable via the FFI, of course, but less satisfying that way. :)

**Comment by achlipala** [comment]
Incoming RPCs are easy to implement, no FFI required.  See Section 10 of the manual.

But are you asking about outgoing RPCs, where an Ur/Web app calls a remote endpoint?

**Comment by fullreset** [comment]
Actually, I do need both, but my question was mostly about incoming RPCs.

I will revisit the manual ...

**Comment by fullreset** [comment]
So I looked, and it didn't make me any wiser.:) Clarification: I need to handle raw connections from a client, which will send me pure JSON. No HTTP headers etc. Hence my assumption that an FFI solution is the only way short of changing the way `transactions X` etc work ...

**Comment by achlipala** [comment]
Oh, I was assuming HTTP connections.  Has it become common to bypass HTTP these days?

**Comment by fullreset** [comment]
Many protocols work without being wrapped inside of HTTP, although some support plain old sockets (TCP) _as well as_ operation over HTTP. Some advantages of plain socket interfaces are interoperation with existing clients, simplicity of building new clients, and reduced overhead on the wire. 

Some random examples include XMPP (Jabber), MSRP, SIP/SIMPLE, STRATUM, JSON-RPC, etc.

**Comment by achlipala** [comment]
I see.  All that might call for extensions to the Ur/Web compiler/runtime.

**Comment by fullreset** [comment]
Using the FFI escape hatch is always a possibility -- and the only way right now -- but support for a wider range of net oriented applications would be interesting... Perhaps a thought for the future. :)
