### ISSUE TITLE
Question about "Duplicate HTTP tag ..."

### ISSUE THREAD

**Issue by fullreset** [urweb/urweb#111]
I came across something that surprised me today; here's a small example that demonstrates the problem.

The error generated is `misfeature.ur:13:46: (to 13:50) Duplicate HTTP tag S/save`.

```
structure S = struct
  fun one () = 
    let
      fun save r = return <xml/>
    in
      return <xml><body><form><submit action={save}/></form></body></xml>
    end
  fun two () =
    let
      fun save r = return <xml/>
    in
      return <xml><body><form><submit action={save}/></form></body></xml>
    end
end

fun main () : transaction page = return <xml>
    <body>
      <a link={S.one()}>one</a>
      <a link={S.two()}>two</a>  
    </body>
  </xml>
```

Shouldn't the HTML tag for each of these `save` instances be unique? Or do things work this way to prevent leaking too much information to the outside world? (I can't imagine why the latter would matter much in the case of Ur -- and in any case module information is already leaked unless some URP rewrites are in effect.)

I would have expected that the tags generated would be something like `S/one_save` or `S/one/save` or other similar ...

**Comment by achlipala** [comment]
First, I'm realizing now that the phrase "HTML tag" is pretty confusing for this concept.  We're actually talking about the URL namespace, which it looks like you did figure out.

Second, no, function names aren't used automatically in generating names for their nested functions, though it would certainly be logically consistent to do so.  However, if you put your functions inside nested submodules, then the names of those modules _would_ be used to generate the URL names.

**Comment by fullreset** [comment]
I used the terminology in the error message, even though I also found it a bit confusing, just to make sure that we were talking about the same thing. :)

This problem occurred when using a functor to generate page views; having encountered this issue I can of course intentionally invent creative and unique names in let functions that are "exposed", but it would make a little more sense if i didn't have to. :)

**Comment by achlipala** [comment]
I've improved the error message, I think, though for now I believe it is best to keep the preexisting convention for URL-prefix generation.
