### ISSUE TITLE
Serve urweb.js and page-specific js as two files?

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#115]
Ur/Web always concats the js "runtime" (urweb.js) to the page-specific js for every page. This is in my opinion sub-optimal. If Ur/Web would add two script tags, one for urweb.js and one for the page-specific js, browsers would be able to cache urweb.js, significantly increasing the responsiveness of the whole site. The first load will have a little bit of extra overhead because of the two http calls required, but this will be minimal.

I would make a PR for this myself, but I have no idea where to start. With a nudge in the right direction I might get started on this, if it's agreed this would be a good change.

**Comment by ashalkhakov** [comment]
Agreed. It will also pave the way to modules and better JS interop.

**Comment by FrigoEU** [comment]
A second optimization would be to minify the js inside urweb.js. After gzip, the difference is about 4kb which is not huge, but it's something.

**Comment by achlipala** [comment]
I wouldn't mind accepting a PR implementing this idea!  Not sure I could get to it very soon myself.  A hint to find the relevant parts of the Ur/Web source would be to grep for `urweb.js` in `.sml` files. `:-)`

**Comment by FrigoEU** [comment]
Yup, that's what I did. A simple way to do this would be to use
Settings.setScripts but that seems kinda wrong. After that I couldn't
figure out where would be the best place to load the file like we do with
the setScripts call.

**Comment by FrigoEU** [comment]
I'll probably get around to this at some point, though I feel it's less of an issue now that I know that urweb doesn't make specific js files per page, which I first assumed it did. Maybe a question for @achlipala : would that be a possibility? Just to get a feel of how hard this would be to implement.

**Comment by achlipala** [comment]
Assuming you are asking about minifying JS: I believe it would be quite simple to call one function to minify one string of unified JavaScrupt code, at one place in the compiler.  That seems to be all that is needed, if you call some off-the-shelf minifier (regrettably added as a compile-time dependency of Ur/Web).

**Comment by FrigoEU** [comment]
@achlipala : sorry I was unclear. I meant how much effort it would take for the compiler to emit a js file per page, instead of the single js file that it emits now. I'm guessing the compiler already has all of the information it needs to figure out exactly what functions a single page needs, but I'm unsure of the actual implementation difficulty.

**Comment by achlipala** [comment]
That change would be medium-effort for me, taking, I'd guess, about 2 hours.  But I'm not sure it would represent an improvement (and it would take quite a few sentences to explain the appropriate changes, to someone not familiar with the Ur/Web compiler).  Are you proceeding under the hypothesis that some quite large functions are required for relatively small fractions of the pages that an Ur/Web app would serve?

I just checked the most complex Ur/Web that I've deployed (serving a few hundred users over the last few months, planning an event that just finished).  The JavaScript code for all generated functions came to about 1 MB, which is sent to the client on first hit and then cached thereafter.  I also checked the second-most-complicated app I've deployed, which was remarkably consistent, with about the same amount of generated JavaScript.  Would you consider that size reasonable to handle monolithically?  Are you planning for apps that would generate significantly more or larger callable JavaScript functions?

**Comment by achlipala** [comment]
OK, thanks for explaining.  It wouldn't be an epic job to implement splitting in the Ur/Web compiler, but I probably wouldn't get to it soon (especially since I think I wouldn't personally use that feature).

**Comment by FrigoEU** [comment]
Ok, totally understand. Thanks a lot for your time. I'll close this now since I know enough, in time I might come back to this with a PR or implementation questions.
