### ISSUE TITLE
Bug in unurlifying

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#117]
I've stumbled across an annoying bug. It shows up when you have a record that you're sending to the server where the first field (in alphabetical order) is of an option-like type, and the second field is of an enum-like type. Here's the smallest example I could make:

``` urweb
datatype bugged = Nothing | Something of int
datatype myDt = One | Two
type myRecord = {Bugged: bugged
               , MyDt : myDt}

fun rpcTarget (t: myRecord) = return ()

val good = {Bugged = Something 4, MyDt = One}
val bad = {Bugged = Nothing, MyDt = One}

fun main () : transaction page = return <xml>
  <body>
    <button onclick={fn _ => rpc (rpcTarget good)}>rpc with good</button>
    <button onclick={fn _ => rpc (rpcTarget bad)}>rpc with bad</button>
  </body>
</xml>
```

When you click on the "rpc with bad" button, you'll get this error:

```
RPC failure: Fatal error: Error unurlifying datatype myDt
```

The error won't happen when MyDt is of a primitive type, nor will it happen when Bugged is the last field in the row. The error also won't happen if you use the Basis.option type, instead of making your own option-like datatype.

**Comment by achlipala** [comment]
Sorry for the delay finally getting to this one!  The fix turned out to be straightforward.

**Comment by FrigoEU** [comment]
That's excellent, I've been running into this one a lot. Thanks!
