### ISSUE TITLE
NUMA support

### ISSUE THREAD

**Issue by xaduha** [urweb/urweb#12]
(this is just out of curiosity, I don't have any Xeon processors handy)

Ur/web doesn't gain as much as other frameworks when used on Xeon

It's still among the leaders when used on EC2

https://www.techempower.com/benchmarks/#section=data-r11&hw=ec2&test=json

and so it was back in Round 9 with i7

https://www.techempower.com/benchmarks/#section=data-r9&hw=i7&test=json

But with Xeon E5-2660 v2 Ur/web loses that edge

https://www.techempower.com/benchmarks/#section=data-r11&hw=peak&test=json

**Comment by achlipala** [comment]
Are you sure it's anything related to NUMA that accounts for Ur/Web's performance in that last test?  Is there some particular change to the generated C code that you're suggesting?

In general, Ur/Web is designed to have quite good interactions with memory systems, by enforcing that most memory addresses in a running server have unique owning threads.

**Comment by xaduha** [comment]
I don't know anything about it, really. I just have a suspicion that something is going on there, 2 CPUs, 40 HT threads, probably underused somehow.

**Comment by achlipala** [comment]
That could very well be the case, but I continue to expect that Ur/Web is among the best performers in using many cores efficiently.  I'd be less surprised to learn that there is some goofy sequential bottleneck that can be blamed on virtualization.  (Or maybe it's a parallel bottleneck that can be blamed on virtualization!)

I'll probably close this issue soon if you don't have a concrete suggestion for a change to Ur/Web.

**Comment by xaduha** [comment]
I don't have any concrete suggestions, if you don't think that there is something wrong with this picture,

https://www.techempower.com/benchmarks/#section=data-r11&hw=peak&test=json&l=mh6o

then it's settled.

**Comment by achlipala** [comment]
I'd love to see Ur/Web doing better on any of the benchmarks where it isn't #1, but personally I've decided not to spend more time on tweaking there for now.
