### ISSUE TITLE
Empty group added in List.groupBy

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#124]
Before I make a PR I'd like to check via an issue: I believe the implementation of List.groupBy is unnecessarily adding an empty group/list. The code:

```urweb
fun groupBy [a] (f : a -> a -> bool) (ls : list a) : list (list a) = 
    let
        fun groupBy' ls acc =
            case ls of
                [] => rev ([] :: acc)
              | x :: xs => 
                let
                    val (ys, zs) = span (f x) xs
                in 
                    groupBy' zs ((x :: ys) :: acc)
                end
    in
        groupBy' ls []
    end
```

should be:

```urweb
fun groupBy [a] (f : a -> a -> bool) (ls : list a) : list (list a) = 
    let
        fun groupBy' ls acc =
            case ls of
                [] => rev acc
              | x :: xs => 
                let
                    val (ys, zs) = span (f x) xs
                in 
                    groupBy' zs ((x :: ys) :: acc)
                end
    in
        groupBy' ls []
    end
```

I don't see any reason for adding the extra empty list there, but I might be missing something.

**Comment by achlipala** [comment]
It's hard to tell what the author @AlexanderAA intended.  I think both interpretations are consistent with the documentation comment.  Let's see if he responds in this thread!  It wouldn't be great to keep alternating between behaviors every year or so. >:)

**Comment by AlexanderAA** [comment]
I prefer the implementation by @FrigoEU - it is shorter and more in line with groupBy implementations in other languages.

**Comment by achlipala** [comment]
OK, so, @FrigoEU, I'd be glad to see a PR now.
