### ISSUE TITLE
[benchmarks] returnText for a fixed string is worse than returnJson returning random values

### ISSUE THREAD

**Issue by xaduha** [urweb/urweb#13]
https://www.techempower.com/benchmarks/#section=data-r11&hw=ec2&test=plaintext&l=mh34

vs

https://www.techempower.com/benchmarks/#section=data-r11&hw=ec2&test=json&l=mh34

**Comment by achlipala** [comment]
I really don't know what goes on with EC2.  However, in case you weren't aware, I'll mention that an important difference between those tests is that "plaintext" uses HTTP pipelining and "json" doesn't.
