### ISSUE TITLE
The urweb logo is potentially offensive

### ISSUE THREAD

**Issue by nikolaipaul** [urweb/urweb#135]
Maybe it is just me but the very first moment I saw the Ur/Web logo, it reminded me of the Reichsadler from Nazi Germany. The shape to my eyes seems very similar. I hope this is just an accident and would strongly agree to a modification.

I'm not sure this is the right place to make such claims and I will remove it if it's inappropriate.

![ur web-logo](https://user-images.githubusercontent.com/25384717/44055263-2412fa46-9f45-11e8-9c28-53cd2d63d32c.png)

**Comment by achlipala** [comment]
Any resemblance certainly is accidental and hasn't been remarked on before, to my knowledge.  I'd want to take some sort of poll of stakeholders before considering a change on these grounds.

**Comment by nikolaipaul** [comment]
I'm a happy user of Ur/Web nevertheless but this was just floating around in the back of my head.

**Comment by achlipala** [comment]
For now, I don't see anything to worry about and will close the issue, but please feel free to raise the issue on the ur mailing list, if you think it warrants a community discussion.
