### ISSUE TITLE
Ignored wildcards hurts local type class instances

### ISSUE THREAD

**Issue by vizziv** [urweb/urweb#14]
I have a code snippet of the following shape. `myClass :: Type` is a class with no ambient instances. The compiler isn't able to solve the type class constraint for `useTheInstance`.

```urweb
let
    val _ : myClass = makeLocalInstance using some parameters
in
    useTheInstance
end
```

Giving the instance a name fixes the problem. I suspect the problem is `CoreEnv.patBinds` ignoring wildcards. Of course, that's the correct behavior for every situation other than resolving type class instances.

I think the desired behavior should be to not ignore the instance, even if it is named with a wildcard. First, it matches the behavior of `fun` declarations. Second, if there's a default instance for the class, then the code will compile successfully but, against expectations, use the default rather than local instance. Then again, maybe using a wildcard to explicitly ignore instances has some utility, such as when matching an expression of type `usefulValue * myClass` and only wanting the `usefulValue`.

**Comment by achlipala** [comment]
That's a funny interaction that I hadn't anticipated, in the desugaring of `val` to pattern matching.  I expect that I'll soon implement the fix you suggest.

**Comment by achlipala** [comment]
Done.
