### ISSUE TITLE
Unexpected runtime exception: "Fail: x.split is not a function"

### ISSUE THREAD

**Issue by DestyNova** [urweb/urweb#141]
Hi, I tried to find existing issues related to this but came up empty. I just started looking at Ur again and going through some tutorials. I quickly managed to create something that compiles without incident but throws an exception at runtime:

```ur
fun newCounter () : transaction xbody =
  x <- source 0;
  return <xml>
    <dyn signal={n <- signal x; return <xml>{[n]}</xml>}/>
  </xml>

fun main () =
  ls <- source ([] : list xbody);
  return <xml>
    <body>
      <button value="Add" onclick={fn _ =>
        l <- get ls;
        c <- newCounter ();
        set ls (c :: l)}/>
      <dyn signal={l <- signal ls; return <xml>{[l]}</xml>}/>
    </body>
  </xml>
```

### Steps to reproduce
1. Compile and run this
2. Click the "Add" button

### Expected result
A compile time error (perhaps due to getting the return expression of the last `dyn` tag completely wrong).

### Actual result
Alert box appears stating:
> Fail: x.split is not a function (http://localhost:8080/app.E0ECB393377D73B677CB96DC5FC1759A954FAAD1.js:1435)

Firefox's debugger shows that the error is thrown from the "else" block of the following function, which expects to take a string as `x`:
```javascript
function eh(x) {
    if (x == null)
        return "NULL";
    else
        return x.split("&").join("&amp;").split("<").join("&lt;").split(">").join("&gt;");
}
```

`x` actually looks like:
```javascript
> x.cat1
Object { cat1: "\n<script type=\"text/javascript\">dyn(\"span\", execD(", cat2: {…} }
> x.cat2
Object { cat1: " :: ", cat2: {…} }
```

**Comment by achlipala** [comment]
What you have run into is definitely a bug, which I will have to look into.  Thanks for reporting it!

Briefly, the extra brackets are taking an HTML fragment, converting it to a plain string, and then escaping that string to inject in a larger HTML context.  Not the sort of thing that shows up often in idiomatic Ur/Web programs, so it makes sense that there would be bugs.

**Comment by DestyNova** [comment]
Thanks @achlipala for the quick and concise explanation! :+1:
