### ISSUE TITLE
SEGV when reading cookie in task

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#143]
Here's a minimal example of the bug:

```
cookie myCookie: {Value: string}

fun main (): transaction page = return <xml></xml>

task initialize = fn () => 
  c <- getCookie myCookie;
  return ()
```

On startup, this will segfault. Not sure what the desired behavior would be: Either you get a more readable error, or you get None. I got it due to a coding error, but I still wanted to point it out since it took me some time to figure out where it came from.

**Comment by achlipala** [comment]
Thanks for pointing out the bug, and it is definitely an Ur/Web bug that I should look into.
