### ISSUE TITLE
Libraries can be included multiple times

### ISSUE THREAD

**Issue by vizziv** [urweb/urweb#15]
Things like loading jQuery multiple times can make things break. (Example: a click event that's supposed to toggle a menu open it will happen twice, so the menu open then immediately closes.) It's easy for this to happen when a library is depended on multiple times. (Example: A depends on B and C, and B also depends on C, where C includes jQuery.)

It'd be nice for Ur/Web to do the "right thing" for `library` declarations in `.urp` files, which is probably to include them only the first time. The one potential stumbling I can see is module name collisions. I don't know how they're dealt with now, but if it's "last module with a given name wins", then later inclusions of a previously included library would have to not be ignored completely.

(This doesn't automatically fix the multiple jQuery problem because multiple libraries could all include jQuery. However, it at least permits a style that would solve it, namely always putting external script dependencies in their own libraries.)

**Comment by achlipala** [comment]
There's already code to avoid including a module multiple times.  I should add similar checking to only include a library the first time it's referenced.

**Comment by achlipala** [comment]
Done.
