### ISSUE TITLE
Pattern for intercepting displaying a page with an extra validation step?

### ISSUE THREAD

**Issue by robinp** [urweb/urweb#153]
I wonder if, and how, could the following pattern be implemented:

Scenario:
- User want to visit a page containing sensitive information (say credit balance).
- I (as developer / webapp) want to suspend showing that information, ask for the password, and if it was correct, resume showing the requested page.

Ideally the suspend-and-resume functionality would be reusable, so I wouldn't have to recode it for each of the various sensitive pages.

One solution coming to mind is explicitly representing the possible sensitive pages/actions in a Sum type, make it serializable, push it to the DB, and on successful auth, pop from the DB and invoke a handler that pattern-matches.

But that sounds kind of manual, going counter to the promise of Ur of high-level flows. Could a reference to the sensitive page, represented as a `transaction page`, be passed as an argument to the handler of the validation form, which would just run it? This sounds like transactions (or their input closure) would need to be persistable somehow..

But maybe you have a more idiomatic solution in mind (maybe involving functors or other magic).

**Comment by robinp** [comment]
Tinkering a bit, I think for GET requests this works:

```sml
fun interceptIf[r] (tb : transaction bool) (i : url -> transaction r) (k : transaction r) : transaction r =
  b <- tb;
  if b then u <- currentUrl;
            i u
       else k
```

**Comment by achlipala** [comment]
I would just make each each sensitive-page handler start with an access-control check, showing an authentication form if the check fails, showing the full page content if the check succeeds.  Is there some serious downside with that approach?

**Comment by robinp** [comment]
My original frustration stemmed from wanting to have a universal access-control check combinator (just as you advise), which would be able to resume the original intended transaction after validation. For `GET` requests, this could work, as a `url` can indicate clearly what transaction to resume.

But for `POST` (or form handlers) this wouldn't work, as a transaction doesn't have a serializable representation, where the flow could resume after validation.

However you could argue that interrupting one `POST` with an auth check is not a very good or sensible practice. For example, a replacement could be a setup where a pre-auth happens when entering a sensitive edit form, along with a timer which tells how long the previous auth is valid (and then form submission could go through uninterrupted).

Unless you have productive comments or experience on this topic, feel free to close, as it sounds like I'm trying to prematurely solve a scenario I didn't really run into yet. Thank you!

**Comment by achlipala** [comment]
OK, I'll go ahead and close.

Let me note that it wouldn't even be necessary to use `url`-typed values with the scheme I proposed.  You can instead pass `transaction page` computations directly, in some cases.  You would get higher-order functions compiled once per different argument, which might be fine for some cases, but does sound like it would run into troubles best solved using `url`s.

I see that this solution doesn't help with saving `POST`ed form results, but I also agree the need for that saving is questionable.
