### ISSUE TITLE
safeGet when all GET handlers have benign side-effects

### ISSUE THREAD

**Issue by robinp** [urweb/urweb#155]
Now `GET` requests shouldn't have side-effects. By the way, what is a side effect exactly (since running in `transaction` is not yet a side-effect)? Doing `DML` surely is, maybe setting cookie as well. Anything else (like doing FFI)?

A problem I face is I would like to add server-side analytics, practically making all handlers (GET or POST nevertheless) log into the DB. This is obviously a benign side-effect (the results only to be used offline later), but implies having to mark all `GET` handlers as `safeGet`, which goes counter the point (now `safeGet` means nothing informative for an auditor).

I wonder what would help here? Maybe a way of marking a `table`, or even just a given `transaction` operation as benign, so it's use wouldn't trigger the side-effect alert?

**Comment by achlipala** [comment]
The side-effect analysis is written to be conservative, so, yes, by default FFI functions will be guessed as side-effecting.  However, there are `.urp` directives to whitelist FFI calls as pure.  Any operation that breaks referential transparency, in the usual functional-programming sense, is meant to be modeled as side-effecting.

I have shared your pain with the simplistic handling of purity and HTTP request methods.  I often `safeGet` many different entry points whose only side effects are changing tables related to authentication, updating last-logged-in timestamps and so forth; or where the side effects only come with registering client-specific change listeners.  It could be nice to have some principled way of understanding what makes these effects benign, but at the moment I have no plans to add that feature.  I would be open to tasteful PRs, though!

In the working version of Ur/Web, you can easily opt out of this checking via the `safeGetDefault` directive that I added quite recently.

**Comment by robinp** [comment]
I wonder if a marker function `benign : transaction t -> transaction t` would make sense from compiler architecture point? Would make compiler omit checking that subtree against side-effect, for the purpose of GET handler safety check.

Lacking that, thanks for `safeGetDefault`, will revert to it if `safeGet`s would become overly painful.

**Comment by achlipala** [comment]
There are a bunch of alternative designs that this discussion indicates could be worth thinking about, but for now I'll take the problem as solved.

**Comment by robinp** [comment]
Had a look at urweb code, for my above mentioned `benign` to work it seems `effectize` would need to skip checking effects of the subtree of the function call, but it also seems that by that phase most of the function names are gone, so it is not easy to just add a setting.

Note: I used the `-dumpSource` urweb flag to dump the AST at the point of the failure, which is an error resulting in `effectize` due to a side-effecting GET handler.
