### ISSUE TITLE
INSERT INTO forces mention nullable fields?

### ISSUE THREAD

**Issue by robinp** [urweb/urweb#156]
Minor inconvenience: It seems if I have a table with an `option string` field `Foo`, then it can't be omitted from the `INTO` list of `INSERT` - I get unification failure if I do so. AFAIR in SQL one can omit mentioning nullable fields, if a value need not be set.

**Comment by achlipala** [comment]
What we have here is a case where I intentionally chose to remove flexibility that standard SQL provides.  If you have a strong argument for bringing this feature into the Ur/Web SQL subset, I'm willing to hear it.  But do keep in mind that almost nothing about SQL is built into Ur/Web, instead being encoded as a library with a uniform type system.  This nonuniformity would show up as complexity in the type of `INSERT` as a combinator.

**Comment by robinp** [comment]
Thanks, makes sense. Was not sure if this was a bug or a feature.
