### ISSUE TITLE
New ord, chr functions crash on IE11 

### ISSUE THREAD

**Issue by fabriceleal** [urweb/urweb#158]
Functions `chr` and `ord` will break the client side on Internet Explorer 11 because I'm using String.fromCodePoint and "...".codePointAt, and these functions were not implement (yet?) in there. I've read that Safari might also break. It doesn't break on Edge.

**Comment by achlipala** [comment]
Is there any kind of easy fix that degrades to approximate behavior, based on checking first whether `fromCodePoint` exists?

**Comment by achlipala** [comment]
And another worthwhile compromise solution could be to at least maintain Ur/Web backward compatibility by checking if a character is ASCII, in which case we do the old simple thing.

**Comment by fabriceleal** [comment]
Yeah was trying to do that `fromCodePoint` check, I'll explore a bit and try to make up a javascript implementation of it. The main issue is that some native javascript operations, like indexing a string, or calling `.length`, will exhibit very weird behavior if it contains chars that require more than 2 bytes for encoding, for instance `"𝌆𝌇𝌈𝌉".length` yields 8, even in chrome for instance

**Comment by fabriceleal** [comment]
ugh ... now I'm even seeing more corner cases for `tolower` that are handled nicely by chrome/firefox but not in IE11 -.-

**Comment by ashalkhakov** [comment]
IE11 is not a priority, I think, as MS has recently decided to switch their engine to the one of Chrome. So I guess we can mostly ignore this. :-)

**Comment by fabriceleal** [comment]
Edge also has some failing cases in `tolower` and `touppper`, and I suspect Safari could as well, but I'm unable to test there. May I create the PR only with the 'dont-break-javascript' fix and maybe create another github issue for `tolower` and `toupper`? don't create an issue at all for it?
