### ISSUE TITLE
Support for decimals

### ISSUE THREAD

**Issue by ashalkhakov** [urweb/urweb#16]
I'd like Ur/Web to have some support for decimal/numeric type.

Any idea how to begin?

**Comment by achlipala** [comment]
It's not obvious how to go about it, since we'd need natural numbers to appear in types.  I would rather not, at this late date, start introducing a type-level copy of the naturals, GHC-style!

Do you have any other ideas?

**Comment by ashalkhakov** [comment]
Yes, I have an idea.

I think Ur/Web program doesn't have to know anything, if at all, about the decimal precision that database backend can handle. That is, there is only one type "decimal" (or "numeric"?), which is used at runtime by Ur/Web code (the so-called "host representation"). The database (aka "storage") representation could be "decimal(10,2)". Then, what we need is a way for programmer to specify that Ur/Web table column Col of type "decimal" maps to SQL table column Col (renamed as usual) of type "decimal(10,2)" somehow. If the value passed at runtime cannot be stored in the database, then it's a runtime error (or, we could always add a column-level CHECK constraint for precision/scale checking, which is very similar to SimpleFeatures checking with geodata). The idea is kind of similar to string handling (I don't think Ur/Web allows to specify fixed length of a VARCHAR column, does it?).

One way would be using some annotations on tables. I guess that would require some syntax extension. For instance, consider this (the syntax is completely made up):

`table t : { Id : int, V : decimal storage { precision=10, scale=2 } } PRIMARY KEY Id`

Another way would be through some compiler configuration, e.g. there already exists an option to disable renaming of SQL tables/columns. What do you think?

**Comment by achlipala** [comment]
Ur/Web doesn't have any official support for VARCHAR, though everything should magically work if the database has been set up using a schema other than the one output by Ur/Web itself, where some string columns have been made VARCHAR.  The same might work for DECIMAL, where the Ur/Web type is float.

I'm unconvinced, though, that this extension is worth the complexity it brings.  It should generally be possible to use an integer type and systematically interpret it as having a fractional part (e.g., the abstraction function from integer to decimal is to divide by a certain power of 10).  It's even possible to use Ur/Web's module system to enforce that a particular column appears to have an abstract type, where the only legal operations are coded to preserve the abstraction.  Would that work for your use case?

**Comment by ashalkhakov** [comment]
> Ur/Web doesn't have any official support for VARCHAR, though everything should magically work if the database has been set up using a schema other than the one output by Ur/Web itself, where some string columns have been made VARCHAR.

**Comment by ashalkhakov** [comment]
> Ur/Web doesn't have any official support for VARCHAR, though everything should magically work if the database has been set up using a schema other than the one output by Ur/Web itself, where some string columns have been made VARCHAR.

This is what I've been doing. Thanks for clarifying that it is indeed the preferred approach.

> It's even possible to use Ur/Web's module system to enforce that a particular column appears to have an abstract type, where the only legal operations are coded to preserve the abstraction. Would that work for your use case?

So, you're saying that I should create the module Decimal (say) that provides an abstract type [t] (plus the necessary typeclass instances for show, inject, etc.), that is actually stored as a decimal in the database? That might actually work. Besides, in my case, it is also necessary to store the associated currency, and bundling the two together might be a good idea.

For now, I'm using the "float" type (kinda nervous about storing money amounts using floating point, but in my country, the decimal point is not actually used, so it should pose any problems). I guess this issue can be closed.

**Comment by achlipala** [comment]
Well, I wouldn't say "VARCHAR" is preferred.  To me it seems like a relic of an age when the SQL programmer needed to get more involved in optimization to achieve acceptable performance.  Length-unlimited string types are probably plenty performant for nearly all applications!

Yes, I'm suggesting creating a Decimal module, abstracting a use of the plain old "int" type.  Actually, you might want to make Decimal a functor, so that a new abstract type is created for every choice of how many decimal digits to include!  You could also fold in a currency choice as another argument to the functor.
