### ISSUE TITLE
Form handlers unprotected against tampering with partially applied parameters.

### ISSUE THREAD

**Issue by robinp** [urweb/urweb#161]
Say I have a form handler `handle  foo record: transaction page = ...`, which I pass to form submits using `<submit action={handle "foo"}/>`. Now the argument `"foo"` is visible in the action url (something like `/Module/handle/foo`), which is not aesthetic. But even more, not tamperproof, since the value is not validated on the server-side, so the client can overwrite with random values.

1) It would be nice if the form signature would include the handler url as well, at least.

2) It would be nicer aesthetics-wise, if the arguments were somehow magically encoded as hidden form inputs.

(Slightly off-topic, the same is true for GET endpoints, but it's kind of acceptable there. I saw a nice solution in the Haxe/Neko language, where continuation transactions were persisted into the DB with a unique ID, and the client only received opaque IDs as links. This needed periodic GC of old (likely never pursued) continuations, but provides no insight into server-side names, arguments etc.)

**Comment by achlipala** [comment]
I'm not clear on what threat model is worrying us here.  What capacity of the attacker calls for handling precomputed handler inputs differently from those filled in via form widgets?  You are just worried about a confidentiality leak, for an attacker who can see URLs but not POST data?  From an integrity perspective, I don't see any difference between the two kinds of inputs.  With the Ur/Web programming model, we are always supposed to assume that attackers are messing with all arguments to handlers.

The aesthetic concerns are another matter, but there, short of a poll, it is hard to tell who is bothered by this convention.  Somehow it has never bothered me.

Regarding your Haxe/Neko example, I find it quite unpleasant to be stashing continuations in persistent storage.  The idea of expiring URLs doesn't seem like a great recipe for a nice user experience, and it raises the garbage-collection implementation and policy challenges that you mention.

**Comment by robinp** [comment]
My frustration seems to stem for assuming a convenient continuation model for programming.

You are true that Ur is not behind other frameworks (not that I know too many of them) in not validating form values - generally, server-side validation is expected if necessary.

OTOH, Ur static (hidden) arguments to forms could easily be protected by a signature. One could argue, that the programmer placed these hidden values since he wants to reuse them on reception. Normally some form of server-side validation would be necessary, if he wants to trust these values. If I'm not mistaken, this could be implemented seamlessly, providing ease and tamper-guarantee for the programmer.

A complication might arise if hidden inputs were set from the client-side. These naturally couldn't be protected (though the usecase is pretty rare, if non-existent, too).

I agree with the opaque links backed by DB-stored continuations is not very elegant, and rather serves niche purposes. Expiring URLs are not a nice experience for GET requests I agree, but for POSTs one could argue that expiry is usually desired (the browser even warns if you want to resubmit a previous POST, which is usually not what you want).

It triggers though a (programmer-side) workaround idea, if the hidden-input-signing doesn't make it into the compiler: Generate the partial arguments, stash them in DB with a random id, and output the random id to a hidden element. This way on reception the arguments could be restored with some confidence of non-tampering (reuse of past values is still some issue, but thoughtful and timely GC could prevent it).

**Comment by achlipala** [comment]
I think we have a philosophical difference here, and it's not clear that we can converge to a useful outcome in this medium.  However, I would welcome a discussion on the `ur` mailing list!  If community consensus is for a change, then it could be a good idea.
