### ISSUE TITLE
urweb flag to print all public endpoints?

### ISSUE THREAD

**Issue by robinp** [urweb/urweb#162]
A flag to output all public endpoints would be useful, for example to verify that all modules are whitelisted for access in the webserver proxy config.

**Comment by ashalkhakov** [comment]
@achlipala could you give a few hints about this? I'm interested in this for the purpose of documenting the APIs implemented with Ur/Web.

**Comment by achlipala** [comment]
In, say, the final Mono-IR version of a program, it's `export` declarations that reveal exactly the callable handlers, with URL prefixes.

**Comment by ashalkhakov** [comment]
I have made [this change](https://github.com/urweb/urweb/compare/master...ashalkhakov:endpoints?expand=1), but there are some things I'd like to clarify:

* how to get Content-Type for all endpoints? (I guess it's not possible in the general case; e.g. an function might returnBlob with different content types in two branches of an [if])
* is this a fine format? there could be others we might want to look into e.g. OpenAPI

**Comment by ashalkhakov** [comment]
[Usage example](https://github.com/ashalkhakov/ashalkhakov.github.com/blob/source/dump.py). This script will read the JSON file containing all GET endpoints, make the requests to a locally-running app, and save them as files. Basically what webscrapers typically do, but we have a list of URIs to visit so there is no need to search for them.
