### ISSUE TITLE
Url rewrite behaves odd when removing last component in url

### ISSUE THREAD

**Issue by robinp** [urweb/urweb#164]
I would like to achieve the following: make `Foo.index` accessible by the url `/foo`, also make any `Foo.bar_baz` accessible by `/foo/bar-baz`.

I add the following rewrite rules. Note that I need to put the `Foo/index -> foo` rewrite first, since urweb only processes rewrites until the first match - putting it second would have no effect, as the rewrite-underscores-to-hyphens rule would catch it first.

```
rewrite url Foo/index foo
rewrite url Foo/* foo/ [-]
```

But now accessing any `/foo/bar-baz` or in fact any gibberish URL under `/foo/` serves the `/foo` page.

Edit: I use the 20180616 release.

**Comment by robinp** [comment]
Ah, so it treats the remaining path as a parameter to `/foo`. That explains the behavior at least.

It sounds reasonable, though it means if I want to set up an easy to memorize structure like `/blog` and `/blog/some-post`, it can't be done. Unless if `/blog` would take on `option string` and then do some magic to select the post, which I would avoid for now.

Other workaround might be `/posts` and `/post/some-post` (though that's prone to users confusing them), or to rewrite the user-facing urls using a proxy (which adds an extra layer of failure though).

A compiler warning would be nice indeed.

**Comment by achlipala** [comment]
a19e53017364ceddbba557fb363ca26b273f89da raises errors when URL prefixes clash.
