### ISSUE TITLE
Exceeded supported UTF-8 range when trying to use palm tree emoji.

### ISSUE THREAD

**Issue by robinp** [urweb/urweb#166]
The &amp;#127796; ( &#127796; ) character's range doesn't seem supported. I get the following error while building:

```
unhandled exception: Fail: Exceeded supported range for UTF-8 characters
```

(Using 20180616 release).

**Comment by ashalkhakov** [comment]
Have you tried building against the master branch? This should be working in the unstable version.

**Comment by robinp** [comment]
I believe you, thanks! Didn't build myself yet, will eventually.
