### ISSUE TITLE
'FreeBSD 10.2' openssl.c:43:3: error: passing argument 2 of 'CRYPTO_THREADID_set_numeric' makes integer from pointer without a cast

### ISSUE THREAD

**Issue by bfilin** [urweb/urweb#17]
While compiling urweb-20151220 source under FreeBSD 10.2:
 executing gmake gives openssl cast error:
sl.lo -MD -MP -MF .deps/openssl.Tpo -c openssl.c  -fPIC -DPIC -o .libs/openssl.o
openssl.c: In function 'thread_id':
openssl.c:43:3: error: passing argument 2 of 'CRYPTO_THREADID_set_numeric' makes integer from pointer without a cast [-Werror]
   CRYPTO_THREADID_SET(result, pthread_self());
   ...

Changing line 43 in src/c/openssl.c seems to solve this:
Changed From: CRYPTO_THREADID_SET(result,  pthread_self());
Changed To: CRYPTO_THREADID_SET(result,  (uintptr_t) pthread_self());

After this small casting change I am able to compile/install urweb-20151220 and then use urweb to compile old program under FreeBSD 10.2. I'm just not 100% sure if this is a correct way to fix this.

**Comment by achlipala** [comment]
I implemented a slightly different fix, based on your suggestion, in a way that retains compatibility with platforms where pthread IDs are pointers.  Thanks for the report!
