### ISSUE TITLE
Performance problem in uw_Basis_stringToBlob_error -> strlen (on OSX)

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#171]
I'm building file uploads into my application. This is the first time I've used blob's in urweb. I've managed to build the upload and the download. However, I'm coming up against a big performance problem in uw_Basis_stringToBlob_error (used . When serving a 600kb file, it takes about 17 seconds to process the request. 

I'm running on MacOS (10.12.6). I've attempted to look a bit closer into where the problem is. I used the "Instruments" profiling tool, and found the problem is in the sscanf call [here](https://github.com/urweb/urweb/blob/91c0e37b0ddc8495e31bd653b8bc363fd14f4375/src/c/urweb.c#L3322). Drilling down further, it goes into vsscanf_l and then to the strlen function (all inside libsystem_c.dylib) that is actually causing the slowdown.

I'm on vacation and only have my OSX laptop with me so I can't test it on my main Linux machine.

I googled a little bit but haven't found any immediate problems with the strlen function on OSX. If there is anything else I can check, please let me know, I'm an absolute noob with these system functions.

**Comment by ashalkhakov** [comment]
Do you have an example somewhere so that I could reproduce it on Linux?

**Comment by FrigoEU** [comment]
Yes of course. Here it is.

**uploadtest.urp**
```
allow mime *
database host=localhost dbname=uploadtest user=postgres
sql sql.sql

main
```

**main.urs**
```
val main: unit -> transaction page
```

**main.ur**
```
sequence filesSeq
table files : { Id: int
              , Content: blob
              , MimeType: string
              }

fun download id: transaction page =
    f <- oneRow1 (SELECT * FROM files WHERE files.Id = {[id]});
    returnBlob f.Content (blessMime f.MimeType)

fun doUpload f: transaction page =
    id <- nextval filesSeq;
    dml (INSERT INTO files
           (Id, Content, MimeType)
         VALUES
           ({[id]}, {[fileData f.File]}, {[fileMimeType f.File]})
        );
    return <xml>
      <body>
        <div>
          <a link={download id} target="_blank">
            Download your file here.
          </a>
          Downloading a file of around 600kb takes about 16 seconds on my Macbook Pro. If you want to upload files bigger than 1MB, run the executable with "-m 10000000"
        </div>
      </body>
    </xml>


fun main (): transaction page = return <xml>
  <body>
    <div>
      Upload your file here:
    </div>
    <form>
      <upload{#File}/><br/>
      <submit action={doUpload} value="Go!"/>
    </form>
  </body>
</xml>
```

On the shell:
```
urweb uploadtest
createdb uploadtest
psql -f sql.sql uploadtest
./uploadtest.exe
```

Navigate to **localhost:8080/Main/main**

There is a similar setup in the demo [here](http://www.impredicative.com/ur/demo/), but that doesnt save files into the database so that won't have the same problems!

**Comment by ashalkhakov** [comment]
I've made a branch [here](https://github.com/ashalkhakov/urweb/tree/issue171) (reusing an existing test case), could you adapt it to run it on Mac against PGSQL? It works very fast with SQLite on Linux and I'm a bit too lazy to install PGSQL at the moment. :-)

**Comment by ashalkhakov** [comment]
Another thought is to enable the filecache (there is a switch in the compiler so that the programs use filesystem for storage of blobs).

**Comment by achlipala** [comment]
Even if Postgres uses an internal file cache, you would not avoid the overhead of transferring all the darn bytes back to the application over a network or UNIX domain socket, which bytes (due to the way libpq works) need to be explicitly encoded and unencoded, as best as I'm able to figure out the options at present.  That's why I put filecache support in Ur/Web.  It is expected that working with files in the database is unmanageably slow without the filecache.

**Comment by FrigoEU** [comment]
As I could tell from Artyom's comments, it is fast on Linux though, which I
think is weird but probably has nothing to do with Ur/Web...

For me personally, I'll run some tests using the - filecache option, and
when I'm back on my production servers. If it only affects Mac and can be
circumvented with -filecache I'll close this.

Simon

**Comment by FrigoEU** [comment]
Using filecache, this does go very fast on OSX. After removing the files in the cache, reloading them goes slow but that's expected of course. 

I'll be closing this, thanks for the help!
