### ISSUE TITLE
Anonymous code at code generation strikes again

### ISSUE THREAD

**Issue by robinp** [urweb/urweb#173]
Short of reopening #144. I was hoping to remove manual passing of a blog post `title` to both the post list and the post page content itself, so wrote the following.

```
type postdata =
  { Title: string
  , Render: string -> transaction page
  }

fun index () : transaction page =
  let val rec gen = fn ps =>
        case ps of
            []       => <xml/>
          | (p::rest) => <xml>
              <li><a link={p.Render p.Title}>p.Title</a></li>
              {gen rest}
              </xml>
  in
    mkPage "Posts" <| return <xml>
      <ul>
        {gen (posts ())}
      </ul>
    </xml>
  end

and posts () : list postdata =
  { Title = "foobar"
  , Render = foobar
  }
  ::
  { Title= "baz"
  , Render= baz
  }
  :: []

and foobar title : transaction page = ...
```

Note that this now complains about `p.Render p.Title` not being a valid link target (which might be due to it can't be inlined enough by the compiler?), but if I replace that with a known static call, I get back the anonymous function error.

It would be nice if you could advise on a pattern that works for this situation, and general guidelines as well. Thank you!

**Comment by robinp** [comment]
Note:

```
fun postLink f t = <xml>
  <a link={f t}>t</a>
</xml>

fun index () : transaction page =
    mkPage "Posts" <| return <xml>
      <ul>
        <li>{postLink foobar "foobar"}</li>
         ...
```
works, but trying the same with `List.mapX` on the record doesn't (due to invalid link target, but that's a different issue). I still wonder if there's a way to avoid manually expanding, and rather work from info stored in a data structure?

**Comment by robinp** [comment]
Ah, actually the `postLink` solution is not satisfying, as it will apply the title as a parameter to the page function on client side (which I know is WAI from Ur/Web perspective, but still annoying). So it would become `/posts/foobar/foobar`.

**Comment by robinp** [comment]
I resolved by

1) accepting that I have to duplicate passing the title. One can argue that the two strings passed are semantically different, even if content-wise the same: one is the title displayed on the top of the post, the other is the one how it is linked. This makes me sleep better. In fact, one needs a stable, argument-less function if wants to hyperlink the function from other places as well.

2) Storing `url` in the record instead `transaction page`, and converting from latter to former using the `url` function on the explicit page handler. Then using `<a href={theUrl}>` instead of `<a link={theTransaction}>`.

**Comment by achlipala** [comment]
I would say the underlying problem here is putting functions in a list to be processed server-side.  Consider that a big no-no, albeit only reported to you by the compiler in a cryptic way!  Instead, put the functions in a tuple and use a row fold to iterate over the tuple.  Basically, tuple recursion is always resolved compile-time, allowing function inlining, while list recursion is always left to runtime.

**Comment by ashalkhakov** [comment]
> Storing `url` in the record instead `transaction page`, and converting from latter to former using the `url` function on the explicit page handler. Then using `<a href={theUrl}>` instead of `<a link={theTransaction}>`.

That's how I do it as well on my [website](https://github.com/ashalkhakov/ashalkhakov.github.com/blob/source/src/index.ur), too: the `url` type can be passed around freely.

**Comment by robinp** [comment]
@achlipala Thanks, will give tuple folding a try! Indeed, urweb could run in a competition against gcc template error messages :) Not that I complain since I asked for it.
