### ISSUE TITLE
Urweb daemon: Save previous modules even if later error?

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#174]
Hey,

I hope the title is not too confusing, but basically I've noticed that the daemon only saves modules if NO errors are found during elaboration. This can pretty seriously slow down development when you have eg: the following .urp:

```
a
b
```
You change something in a and b. You recompile and errors are reported. You correct a. From then on, every recompile will keep recompiling a until b elaborates without errors. Would it not be better if a is saved in the daemon once its own elaboration phase is correct? Or am I missing something here? I'm pretty sure I am, but I'd still like to know what it is...

I've spent some time trying to get familiar with the compiler codebase, so I'd be more than willing to make a PR for it.

**Comment by achlipala** [comment]
This one is a bit tricky, because the types inferred for `a` might have been influenced by erroneous types inferred in `b`.  To do right, it would take some kind of analysis to rule out such cases.

Are you seeing long enough compile times on modules as you develop them like this, to justify the extra compiler complexity?

**Comment by achlipala** [comment]
To give an example about (perhaps counterintuitive) influence backwards in your list of included modules: `a.ur` could include a line `val my_list = []` (leaving the element type unspecified), then `b.ur` could include `val my_further_list = 1 :: A.my_list` (implying the type of `A.my_list`).

**Comment by FrigoEU** [comment]
Ugh yeah I figured it was something like that... It would for sure help me
a lot, my project is growing bigger and bigger everyday. On my 2015 MBP
full elaboration takes around 40 seconds. It's not impossible to work with,
but it is annoying. It's one of two reasons why I don't run the compiler
constantly in my editor. (the second reason is that the daemon basically
stops working when you run two builds in parallel, but that's another
story).

Now that I think of it, would it be possible to do the changr I suggested
as long as the module has a signature? That way inference wouldn't be able
to cause module a's result to be incorrect, right?

Simon

**Comment by achlipala** [comment]
Yeah, I can believe there could be a relatively simple signature check to make sure later modules can't cause side effects on it.  The language does allow `_` wildcards in signatures, so you'd have to check that they aren't present.  I'd be open to a PR in this vein.

**Comment by FrigoEU** [comment]
I have this working, apart from the detection of _ wildcards in signatures. Is there any trace of these in the "elab" structures? Or do I have to search through the "source" structures? It would be easy to use the elab_util functions to crawl through, but the source structures don't have corresponding functions like that I think. Any tips?

**Comment by achlipala** [comment]
As I think about it now, I don't ever write wildcards in signatures myself, so what would you think of just banning them?  I'd run the idea past the mailing list before proceeding.

**Comment by FrigoEU** [comment]
100% for it. I never use it in signature files.

**Comment by FrigoEU** [comment]
#174 and #186
