### ISSUE TITLE
SQL: <> {[None]} is incorrect

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#175]
The following Embedded SQL statement:

`SELECT * FROM mytable WHERE mytable.myfield <> {[None]}`

gets compiled to 

`SELECT * FROM uw_mymodule_mytable WHERE uw_mymodue_mytable.uw_myfield <> NULL`

This should get compiled to:

`SELECT * FROM uw_mymodule_mytable WHERE uw_mymodue_mytable.uw_myfield IS NOT NULL`

Or equivalently: 

`SELECT * FROM uw_mymodule_mytable WHERE NOT (uw_mymodue_mytable.uw_myfield IS NULL)`

I think we should either disallow this `<> {[None]}` and add IS NOT NULL to the parser, or fix the codegen resulting from `<> {[None]}` though i haven't been able to figure out where the compiler corrects the codegen for `= {[None]}`.

**Comment by achlipala** [comment]
Null semantics in SQL are a constant headache, but in this case I was trying to preserve them literally in Ur/Web.  Standard-library function `Top.eqNullable` is meant to be used when you want a more intuitive semantics.  What do you think?

**Comment by FrigoEU** [comment]
Oh I see. I just read this comment in basis.ur:

`
val sql_eq : t ::: Type -> sql_binary t t bool
(* Note that the semantics of this operator on nullable types are different than for standard SQL!
 * Instead, we do it the sane way, where [NULL = NULL]. *)
`

So I figured that would also be the case for <>. I'm fine with how it is now as I use (x IS NULL) and NOT (x IS NULL) just to be sure. I had not heared of Top.eqNullable so maybe a reference to that function in the basis library would be useful?

**Comment by achlipala** [comment]
It looks like I let that comment get out-of-date.  Both polarities of equality seem to be compiled to normal SQL equality now.  I think it was somehow more trouble than it was worth, to expose SQL literally, except for changing equality semantics.

**Comment by FrigoEU** [comment]
OK, that makes sense. Thanks!
