### ISSUE TITLE
Cryptic error message "Bad path kind spec" when invalid rewrite rule in .urp

### ISSUE THREAD

**Issue by DestyNova** [urweb/urweb#178]
I don't really understand how the rewrite command in .urp files works, and added one like this:
```
rewrite AppName/main /
```
What I really wanted was:
```
rewrite url AppName/main
```

Doing it the first way produces this error when trying to compile the program:
```
Bad path kind spec
```
This was a bit mystifying, since I tried compiling it some time after making the change to the .urp file. It would be better if the error message specifies the .urp file and the line number of the directive being processed.

**Comment by achlipala** [comment]
My first thought is to print the bad kind spec, which in this case would be `AppName/main`.  Would that be enough of an improvement, do you think?

**Comment by DestyNova** [comment]
Yes, that would make it much easier to track down. :+1:
