### ISSUE TITLE
Optimizer is too eager

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#179]
Just wrestled with this one. Took me a long time to figure out what it was and to get to a minimal example, but I made it!

```urweb
fun test (i: list int) : transaction unit =
    a <- return (Some "abc");
    c <- (case a of
            None => return "1"
          | Some b =>
            debug "not happening :(";
            return "2"
         );
    (case i of
       [] => return ()
     | first :: _ => debug c)
    

fun main (): transaction page =
    return <xml>
      <body>
        <button onclick={fn _ => rpc (test [])}>click</button>
      </body>
    </xml>
```

I finally figured out that the compiler throws the whole (`case a of ...`) statement away in case `i` is empty. It decides you don't need `c` in that case, but some effectful stuff can be happening in there! I'm illustrating it with debug now, but in my application it was actually a database write that wasn't happening in the payment processing part of my app. (fyi I had enough monitoring and logging that I didn't lose any data, phew).

Another observation I made, which to me indicates that this probably is a bug, is that if you change the result type of the (`case a of ...`) statement to int (`"1"` -> `1` & `"2"` -> `2`) and instead `debug (show c)`, the generated code changes and the `"not happening :("` string is getting printed even when the array you pass is empty.

I haven't looked into the solution myself, or in which phase of the compiler this happens, I just wanted to get the issue written down first...

**Comment by achlipala** [comment]
Thanks for the report.  I agree it's a bug and will try to look into it soon.
