### ISSUE TITLE
Trouble with x-www-form-urlencoded parsing

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#181]
Hi,

I've been trying to integrate with Mailgun. More specifically, they have a service that receives emails and then forwards them via an HTTP x-www-form-urlencoded POST to your webserver. 

I have a route, that asks for a Basis.postBody variable. So far so good, but parsing of Mailgun's form fails. A shortend example of what Mailgun sends:

```
recipient=localhost%40mg.classy.school&sender=jon.johnson%40gmail.com&subject=Re%3A+a+test&from=Jon+Johnson+%3Cjon.johnson%40gmail.com
```

This form seems to be OK: I've tried multiple online decoding "services" and they all have no problem with the format. However when using Top.postFields I get the following error:

```
Invalid escaped URL byte starting at: .school
```

I've traced this to the following lines in urweb.c:
```
static uw_Basis_string uw_unurlifyString_to(int fromClient, uw_context ctx, char *r, char *s) {
...
  for (s1 = r; *s2; ++s1, ++s2) {
    unsigned char c = *s2;

    switch (c) {
...
    case '.':
      if (!fromClient) {
        if (s2[1] == 0)
          uw_error(ctx, FATAL, "Missing first character of escaped URL byte");
        if (s2[2] == 0)
          uw_error(ctx, FATAL, "Missing second character of escaped URL byte");
        if (sscanf(s2+1, "%02X", &n) != 1)
          uw_error(ctx, FATAL, "Invalid escaped URL byte starting at: %s", uw_Basis_htmlifyString(ctx, s2));
...
      }
...
    }
  }

```

This was added in commit 25792a154d53d515917c41256610a03a0a9de5f9 and the changelog says:

```
- Changed URL escaping convention, to avoid confusing proxies.
  The new convention is like the normal one, but with '.' instead of '%'
```

I'm very happy that I found this commit message! However, I'm not sure what to do now. From the changelog, this seems to be a convention internal to Ur/Web. However, we seem to be doing this also when receiving forms from external sources when requesting a postBody. 

What confuses me is that we only run this code if the variable "fromClient" is false...This function is being used in cjr_print.sml, in function unurlify. This is however mostly being called with fromClient = false... Only at https://github.com/urweb/urweb/blob/56bb940f305fb3d32cc218a6dbc8fa1b1fd7ef89/src/cjr_print.sml#L2983 is it being called with True... So that's basically as far as I got. I need Urweb to do parsing with fromClient = true for my mailgun integration but don't know how to get there.

Thanks for any help!

**Comment by achlipala** [comment]
Thanks for finding this issue.  Looks like it was an ill-advised shortcut to reuse the `uw_Basis_unurlifyString` function in `uw_Basis_firstFormField`, in `src/c/urweb.c`!  (As you noted, there are different relevant escaping conventions.)  It's probably a relatively simple fix.  Care to take a shot before I get to it?

**Comment by FrigoEU** [comment]
Aha yes that makes sense! My C skills are abismal, but I might be able to
cobble together a version based on uw_Basis_unurlifyString. I'll send a pr
(that will probably need some fixing).
