### ISSUE TITLE
Default content for missing .urp files?

### ISSUE THREAD

**Issue by docelic** [urweb/urweb#187]
I recently saw this comment from Adam:

"I sometimes use .ur files without .urs files when the only definitions are type definitions and the like, where the .urs file would be literally the same code. Is there any chance of supporting those sorts of modules as well?"

Following up on this, would it be a nice addition to relax requirement on x.urp files as well, so that if they are missing, they default to one line containing "x"?

**Comment by achlipala** [comment]
The compiler does already simulate that behavior when you invoke it with `X` where `X.ur` exists but `X.urp` does not.  Are you suggesting a broader implementation of this pattern, applying also to uses of the `library` directive to include `.urp` files recursively?

**Comment by docelic** [comment]
Ah indeed, thanks for the tip.
I was unaware there was a difference in behavior with libraries, but yes, it is with libraries where it seemed default contents would be useful.

**Comment by docelic** [comment]
Speaking of which, I found the documentation in the Reference Manual describing the behavior with (a) libraries and (b) FOO.ur, but I can't explain behavior (b) with missing FOO.urp:

I start with a basic Hello, World! example saved to `hello.ur`. Then:

1) If `hello.urp` is present, everything works as expected:

```
$ cat hello.urp
hello

$ urweb -endpoints e hello

$ cat e
{"endpoints":
 [{"method": "GET", "url": "/app.DA39A3EE5E6B4B0D3255BFEF95601890AFD80709.js", "content-type": "text/javascript"},
                                                                                                                  
   {"method": "GET", "url": "Hello/main", "content-type": null}]}
```

2) If I add a manual "rewrite" as the Manual says, it also works:

```
$ cat hello.urp
rewrite all Hello/*

hello

$ urweb -endpoints e hello

$ cat e
{"endpoints":
 [{"method": "GET", "url": "/app.DA39A3EE5E6B4B0D3255BFEF95601890AFD80709.js", "content-type": "text/javascript"},
                                                                                                                  
   {"method": "GET", "url": "main", "content-type": null}]}
```

3) But if I remove `hello.urp`:

```
$ urweb -endpoints e hello

$ cat e
<empty>

$ curl 0:8080/main # => Not Found
$ curl 0:8080/Hello/main # => Not Found
```
