### ISSUE TITLE
Support for meta charset=""

### ISSUE THREAD

**Issue by docelic** [urweb/urweb#188]
How should `<meta charset="utf-8"/>` be specified to have it work?

I notice that the definition for `meta` does not support charset, and I found a project where its signature was replaced with this:

```
val meta : unit -> tag [Nam = meta, Content = string, Id = id, Charset = string, Property = string] head [] [] []
```

However it fails with error:

```
hello.ur:0:0: (to 0:0) Unmatched signature item
Item: 
val meta :
 unit ->
  tag
   ([Nam = meta, Content = string, Id = id, Charset = string, 
      Property = string]) ([Head = ()]) ([]) ([]) ([])
```

Could a correct version of this be added to the sources before the upcoming release maybe?

**Comment by achlipala** [comment]
The Ur/Web implementation already takes responsibility for indicating UTF-8 for *all* pages.  There is no need to do anything explicit in source files.  Are you seeing UTF-8 failing to take effect for some application?

**Comment by docelic** [comment]
No problems that I stumbled upon, I was just wondering why the common attribute `meta` wasn't supported. Since I didn't intend to put any value other than UTF8, I will close the issue.
Thanks!
