### ISSUE TITLE
FastCGI: Basis.debug

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#189]
I've hit a bit of a wall here: Basis.debug doesn't seem to work when I'm running my server in FastCGI mode. However, the string "Database connection initialized" does get printed! And that goes through the same log_debug function in fastcgi.c (I think), as "DEBUG: " gets prefixed to it. I don't understand why that works and my Basis.debug calls don't, and I don't understand what the code in log_debug means... 

I'm not getting any errors, the logs just aren't appearing. I'm using Nginx, and spawn_fcgi if that makes any difference.

Any help, or a direction in which I can look further would be amazingly appreciated!

**Comment by FrigoEU** [comment]
Nevermind, for some reason they got sent to the main nginx process's stderr!

**Comment by achlipala** [comment]
Yeah, I remember some inconsistency there that I wasn't motivated enough to correct.  I'd be happy to receive a PR for it, however!
