### ISSUE TITLE
Arguments to root are not mapped correctly

### ISSUE THREAD

**Issue by uweg** [urweb/urweb#195]
Handler:
```
fun test (a: string) : transaction page =
  return <xml>
    {[a]}
  </xml>
```

Rewrite directive:
```
rewrite url Test/test
```

The page is accessible under `http://localhost:8080//abc` while I would expect it to be accessible under `http://localhost:8080/abc`

**Comment by achlipala** [comment]
Interesting.  I think I was never intending for it to work to rewrite page URLs to the empty string.  Maybe it would even be a compile-time error in the presence of even a single other page handler.  No two function URL prefixes should be in a prefix relationship themselves.

Probably the best "fix" here is a documentation change, but I'm not sure which.

**Comment by uweg** [comment]
I see your point. Is there a way to achieve something similar? Meaning: Create some sort of a dynamic page handler that handles URLs not handled otherwise and is able to access the path information.

I'm playing with the idea of building a little CMS.

**Comment by achlipala** [comment]
You can use a frontend web server to implement various hidden rewritings.  Would that suffice for your use case?

**Comment by uweg** [comment]
Yes, that is the same idea I came up with. I haven't tried it yet but I see no reason for it not to work.
