### ISSUE TITLE
Choice of DES for Basis.crypt implementation

### ISSUE THREAD

**Issue by AlexanderAA** [urweb/urweb#20]
Are there any specific reasons for using DES_fcrypt for Basis.crypt? Could DES be replaced with some other algorithm? What would be the requirements for such change to be included into the main repository?

**Comment by achlipala** [comment]
I don't think there's any particular criterion for which algorithm is used there, though changing it could break old code that already has `crypt` outputs in databases.

**Comment by AlexanderAA** [comment]
Closing for now
