### ISSUE TITLE
"||" has higher precedence than "&&"

### ISSUE THREAD

**Issue by mdempsky** [urweb/urweb#202]
In Ur, `False && False || True` evaluates to False. This is because `||` has higher precedence in urweb.grm than `&&`.

Skimming over https://rosettacode.org/wiki/Operator_precedence and also manually checking a few not listed (SML, SQL), I haven't found any other languages where this is the case. Most languages give greater precedence to their logical "AND" operator (most relevant to Ur/Web: C, SML, OCaml, Haskell, SQL, JavaScript), or otherwise give them equal precedence (e.g., BASIC).

Changing this would be backwards incompatible, but at least looking at the Ur/Web standard library, github.com/urweb projects, and achlipala/frapapp, I couldn't find any expressions that combined `||` and `&&` and weren't already using explicit parentheses. (Notably they were all of the form `_ || (_ && _)`.)

**Comment by achlipala** [comment]
I'm certainly open to changing to match common practice in other languages.  Let me check on the mailing list if anyone objects.  (I expect some combination of eerie silence and "+1" comments.)
