### ISSUE TITLE
Some keywords can probably be predeclared identifiers instead

### ISSUE THREAD

**Issue by mdempsky** [urweb/urweb#204]
One frustration I ran into writing my first Ur/Web project was that `Name` is a keyword, so it can't be used as a table column name or record field name. I think this could be avoided by changing `Name` from a keyword into a predeclared identifier. (E.g., in Go, builtin types and functions are handled this way; keywords are only used when needed for parsing.)

This likely applies to `Type` and `Unit` too, and *maybe* `map` as well (which would allow renaming `mp` to `map`).

I tried experimenting with this by changing `FooEnv.empty`'s definitions from `val empty = { ... }` to `val empty = pushKRel { ... } "Name"`, but I'm getting errors in elaboration. I'd guess I'm messing up `kname` or environments somewhere, but I don't immediately see how. WIP commit is at https://github.com/urweb/urweb/commit/70ac4caf641aa2d153b4df3ad6f6ecb262dd368c if anyone wants to take a look and advise where I might have went wrong.

**Edit:** Realized an easier way to implement this: #205.

**Comment by mdempsky** [comment]
https://github.com/mdempsky/urweb/commit/c161935f470917f825431d17420346ba96dcfd46 similarly removes the `map` keyword, so that the standard library functions can be named `map` instead of `mp`.

Not included in the PR at the moment, but I can easily add it or create a separate PR for it if desirable.

**Comment by mdempsky** [comment]
So I thought of a cleaner way to remove the `map` keyword:

1. Rename the `map` keyword to something otherwise invalid like `$$map`. (Optionally: make it an error to use this keyword in user source code, so this remains an implementation detail.)

2. Add to basis.urs: `con map = Dom ==> Ran ==> fn (f :: Dom -> Ran) => $$map f`

I think this is conceptually slightly cleaner from the end-user's point-of-view, because it makes `Basis.map` into a predeclared type-level function like any other. In particular, users can locally shadow it, but then still refer to the builtin version as `Basis.map`.

--

However, it seems like there's something unusual about putting the definition in basis.urs that's preventing this from working with onlineconf.

For example, with unmodified Ur/Web, this source compiles fine:

```
con mymap = Dom ==> Ran ==> fn (f :: Dom -> Ran) => map f

type t = $(mymap (fn a => int) [A = source bool])

val main (r : t) : transaction page = return <xml><body/></xml>
```

It also compiles fine if you move the `mymap` declaration into top.ur+top.urs.

But if you move it into basis.urs, you get:

> Input to exported function 'main' involves one or more types that are disallowed for page handler inputs: Basis.mymap, Basis.source

**Comment by achlipala** [comment]
Yeah, `map` is treated pretty specially (e.g., rewrite rules applied during type inference), so I'm not surprised if some parts of the code expect it to be used directly.  Probably your original strategy is more pragmatic, in terms of minimizing implementation changes.

Let me run this overall idea past the mailing list to see if anyone objects or has suggestions.
