### ISSUE TITLE
Assertion `c->mode == USED' failed.

### ISSUE THREAD

**Issue by mdempsky** [urweb/urweb#206]
I'm running into this runtime crash:

```
vote.exe: urweb.c:3749: uw_commit: Assertion `c->mode == USED' failed.
Aborted (core dumped)
```

I'll try to create a minimal reproducer, but for now a few details that might be relevant:

1. I have an app configured with `timeout 10` and a periodic task that sends messages to all active clients every 5 seconds.
2. My app doesn't use FFI or any features that I would reasonably expect to subvert memory safety.
3. I'm using sqlite.
4. I'm able to ~fairly~ reliably trigger the crash with just ~a few clients~ one client.

**Comment by mdempsky** [comment]
Here's my best minification:

`crash.urp`:

```
database dbname=crash.db
sql crash.sql
safeGetDefault
rewrite url Crash/main
timeout 10

crash
```

`crash.ur`:

```
table active : {
      Client : client,
      Channel : channel unit,
} PRIMARY KEY (Client)

val refresh : transaction unit =
    queryI (SELECT active.Channel FROM active)
	   (fn r => send r.Active.Channel ())

task periodic 5 =
  fn _ => refresh

fun loop m = m; loop m

val main : transaction page =
    me <- self;
    ch <- channel;
    dml (INSERT INTO active(Client, Channel) VALUES ({[me]}, {[ch]}));
    refresh;

    return <xml>
      <body onload={spawn (loop (recv ch))}>
	hello
      </body>
    </xml>
```

First build, create the sqlite database, and start the web server:

```
urweb -dbms sqlite crash
sqlite3 crash.db < crash.sql
./crash.exe
```

Then load `http://localhost:8080` and then refresh.

You should see `Processed request for messages by client 4` and then `Processed request for messages by client 5`.

Wait about 10 seconds, and the server will crash with:

```
crash.exe: urweb.c:3749: uw_commit: Assertion `c->mode == USED' failed.
Aborted (core dumped)
```

**Comment by mdempsky** [comment]
I can reproduce the crash with postgres as well.

**Comment by mdempsky** [comment]
FWIW, I was able to reproduce the issue without the periodic task. Repeatedly curl'ing a URL that invokes `refresh` while repeatedly refreshing the `main` page in the browser eventually hit the same crash.

(I haven't tried since cf20d73 though; I just now noticed that was committed.)

**Comment by achlipala** [comment]
Yup, I've been thinking about precisely the issue you mentioned for the last hour, and I'm about to attempt a fix!

**Comment by Mint-6263** [comment]
@mdempsky
