### ISSUE TITLE
Extended plane Unicode characters mangled when interpolated into HTML

### ISSUE THREAD

**Issue by mdempsky** [urweb/urweb#207]
This test program:

```
val s = "𝕬" (* U+1D56C *)

val main x : transaction page =
    return
	<xml>
	  <body>
	    <p>𝕬</p>
	    <p>{[s]}</p>
	    <p>{[if x then s else s]}</p>
	  </body>
	</xml>
```

gets rendered in the browser as:

> 𝕬
>
> 𝕬
>
> 핬

It seems like 𝕬 (U+1D56C) is getting truncated to 16-bits somewhere, which causes it to render as 핬 (U+D56C).

**Comment by mdempsky** [comment]
This renders correctly though:

```
	    <p>{if x then <xml>𝕬</xml> else <xml>𝕬</xml>}</p>
```

**Comment by achlipala** [comment]
I can confirm where the issue is in the code, though it concerns the extensive Unicode work that @fabriceleal did, which I don't fully understand.

I believe, in `src/c/urweb.c`, you'll find the behavior in `uw_Basis_htmlifyString_w()` (called to escape the `if` result as HTML), which in turn calls `uw_Basis_htmlifySpecialChar_w()`.  I'm not sure the latter function should even exist anymore.

(The inconsistency across your three cases arises from whole-program optimization.  Without the `if`, the compiler is smart enough to run HTML escaping itself in-advance, apparently using a more-correct method.)

**Comment by mdempsky** [comment]
It looks like the issue is the call to `u_strToUTF8` in `uw_Basis_htmlifySpecialChar_w`. That function is for converting UTF-16 to UTF-8, but we have a `UChar32` to htmlify (hence the unsafe cast to `UChar*`). Changing it to use `U8_APPEND` like elsewhere seems to fix the issue.

Looking at this, I'm seeing a handful of other issues though:

1. `uw_Basis_ofUnicode` also uses `u_strToUTF8`. Users might be surprised their 64-bit Ur `int`s are getting truncated to 16-bits. (Within the Ur/Web standard library, it's only used by json.ur, which only needs 16-bit Unicode values anyway; but it could be used by user code directly.)

2. It allocates only 3 bytes, and `u_strToUTF8` has the questionable API that it only emits a NUL terminator when it will fit (whereas `uw_Basis_string`s are expected to always be NUL terminated), and some UTF-16 characters can take 3 bytes when encoded as UTF-8. For example, this program:

       val s : string = Json.fromJson "\"\\uD55C\\uD55C\\uD55C\\uD55C\""
       val main : transaction page = return <xml><body>{[s]}</body></xml>

   should output "한한한한", but it outputs "한�o한�o한�o한한" when I run it.

3. Incidentally, it looks like extended plane characters are supposed to be encoded as UTF-16 surrogate pairs in JSON, but json.ur doesn't check for this. Though I can see arguments either way here.

4. `uw_Basis_chr` checks for `n` being too large, but doesn't check if it's negative. I'm assuming the expected invariant within Ur is that a `char` is always a valid 21-bit Unicode code point.

I can send a PR to address all of these later. Thought I'd note them first in case you have any feedback on these before I work on it.

**Comment by achlipala** [comment]
Thanks for the thorough audit!  I hope @fabriceleal can weigh in, as the author of (most of) the code in question.

**Comment by fabriceleal** [comment]
Hi sorry for the delay :) I will take a look this weekend.

**Comment by fabriceleal** [comment]
Looks ok to me! :)
