### ISSUE TITLE
"limit inputs 1" in .urp file causes invalid pointer error on form submission

### ISSUE THREAD

**Issue by AlexanderAA** [urweb/urweb#21]
Add "limit inputs 1" into app.urp, compile, run, submit a form with two inputs
```
*** Error in `./app.exe': realloc(): invalid pointer: 0x00007f0acc001070 ***
```
Expected result would be HTTP 400 "Bad request - allowed inputs limit exceeded"

**Comment by achlipala** [comment]
That's definitely a bug.  I hope to look into it soon.

**Comment by achlipala** [comment]
OK, should be fixed now.  You'll get an error message when the server process starts up.
