### ISSUE TITLE
urweb site/documentation is unavailable at the moment

### ISSUE THREAD

**Issue by vadzimt** [urweb/urweb#22]
Excuse me if that is inappropriate place to bring that issue, but Urweb's site http://www.impredicative.com/ur/ is unavailable for a few days. Could someone affiliated with project contact site owner to make it or at least documentation available for public use? 

Thank you!

**Comment by achlipala** [comment]
Sorry about that.  Fixed now.

**Comment by vadzimt** [comment]
Thanks!
