### ISSUE TITLE
problems building on devuan beowulf

### ISSUE THREAD

**Issue by choltreppe** [urweb/urweb#237]
Hi there,

I'm trying to build the compiler on devuan beowulf, using the debian packaging, but when I run "make" I get these errors:

`Making all in src/c
make[1]: Entering directory '/tmp/debian-urweb-20200209-dfsg/src/c'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/tmp/debian-urweb-20200209-dfsg/src/c'
make[1]: Entering directory '/tmp/debian-urweb-20200209-dfsg'
mkdir -p xml
mlton  -output xml/parse xml/parse.sml
/usr/bin/ld: /tmp/fileCBGaQq.o: relocation R_X86_64_32S against hidden symbol `staticHeapI' can not be used when making a PIE object
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(gc-npi.o): relocation R_X86_64_PC32 against symbol `getrusage@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(platform-npi.o): relocation R_X86_64_PC32 against symbol `exit@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(linux-npi.o): relocation R_X86_64_PC32 against symbol `fseek@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(util-npi.o): relocation R_X86_64_PC32 against symbol `fflush@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(bug-npi.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(write-npi.o): relocation R_X86_64_PC32 against symbol `write@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(close-npi.o): relocation R_X86_64_PC32 against symbol `close@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(read-npi.o): relocation R_X86_64_PC32 against symbol `read@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(lseek-npi.o): relocation R_X86_64_PC32 against symbol `lseek64@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(Stat-npi.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(open3-npi.o): relocation R_X86_64_PC32 against symbol `open64@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(Error-npi.o): relocation R_X86_64_PC32 against symbol `__errno_location@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(isatty-npi.o): relocation R_X86_64_PC32 against symbol `isatty@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libmlton.a(Stdio-npi.o): relocation R_X86_64_PC32 against symbol `fwrite@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libgdtoa.a(strtof-npi.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libgdtoa.a(strtodg-npi.o): relocation R_X86_64_PC32 against symbol `memcpy@@GLIBC_2.14' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libgdtoa.a(gmisc-npi.o): relocation R_X86_64_PC32 against symbol `__stack_chk_fail@@GLIBC_2.4' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libgdtoa.a(hexnan-npi.o): relocation R_X86_64_32S against hidden symbol `hexdig_D2A' can not be used when making a PIE object
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libgdtoa.a(misc-npi.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libgdtoa.a(sum-npi.o): relocation R_X86_64_PC32 against symbol `memcpy@@GLIBC_2.14' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libgdtoa.a(gethex-npi.o): relocation R_X86_64_32S against hidden symbol `hexdig_D2A' can not be used when making a PIE object
/usr/bin/ld: /usr/local/lib/mlton/targets/self/libgdtoa.a(smisc-npi.o): relocation R_X86_64_PC32 against symbol `__stack_chk_fail@@GLIBC_2.4' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
MLton 20210117 raised: Fail: call to system failed with Fail: exit status 1:
cc -o xml/parse /tmp/fileTVDjgZ.o /tmp/fileCBGaQq.o -L/usr/local/lib/mlton/targets/self -lmlton -lgdtoa -lm -lgmp -m64 -Wl,-znoexecstack
make[1]: *** [Makefile:909: xml/parse] Error 1
make[1]: Leaving directory '/tmp/debian-urweb-20200209-dfsg'
make: *** [Makefile:431: all-recursive] Error 1`

**Comment by achlipala** [comment]
Good heavens!  Do you see the same behavior compiling a trivial SML program with MLton?  This could be more of a MLton bug than an Ur/Web bug.

**Comment by choltreppe** [comment]
I already worked around this by getting it from old repos.
sorry for not editing my post earlier, and thanks for your effort
