### ISSUE TITLE
Does not compile with recent MLton

### ISSUE THREAD

**Issue by AlexanderAA** [urweb/urweb#27]
https://github.com/MLton/mlton/commit/dc182ecde85f5cb4171cf4209a551617fa16c582

```
mlton  -mlb-path-var 'SRC /usr/ports/pobj/urweb-20160515/urweb-20160515/src' -mlb-path-var 'BUILD /usr/ports/pobj/urweb-20160515/urweb-20160515/src' -output bin/urweb src/compiler.mlb
Error: src/main.mlton.sml 249.39.
  Function applied to incorrect argument.
    expects: [Word8Vector.vector]
    but got: [Word8.word vector]
    in: Word8VectorSlice.full (Vector.map (Word8.fromInt o ord) s)
Error: src/main.mlton.sml 275.51.
  Function applied to incorrect argument.
    expects: [Word8.word vector]
    but got: [Word8Vector.vector]
    in: (Vector.map (chr o Word8.toInt))   ...  ecvVec (sock, 1024))
Error: src/main.mlton.sml 348.29.
  Function applied to incorrect argument.
    expects: [??? vector]
    but got: [Word8Vector.vector]
    in: Vector.length v
Error: src/main.mlton.sml 352.42.
  Function applied to incorrect argument.
    expects: [Word8.word vector]
    but got: [Word8Vector.vector]
    in: (Vector.map (chr o Word8.toInt)) v
Error: src/main.mlton.sml 353.60.
  Function applied to incorrect argument.
    expects: [??? vector]
    but got: [Word8Vector.vector]
    in: Vector.length v
Error: src/main.mlton.sml 353.45.
  Function applied to incorrect argument.
    expects: [??? vector] * _
    but got: [Word8Vector.vector] * _
    in: Vector.sub (v, Vector.length v - 1)
compilation aborted: parseAndElaborate reported errors
```

**Comment by karsar** [comment]
It might be useful to elaborate, urweb version 20160515 successfully compiled with MLton 20130715 (their latest announced release, we don't talk about experimental versions I hope) on my Ubuntu 14.04.4 LTS.

**Comment by AlexanderAA** [comment]
Yes, we are talking about MLton master branch, not release.
MLton/mlton@dc182ec

It might be too early to talk about changes to Ur/Web now. However, new MLton release might become available in the next few months (https://github.com/MLton/mlton/issues/147).

**Comment by MatthewFluet** [comment]
The errors in Ur/Web relative to MLton `master` are likely due to MLton/mlton#45.

You could use `MLton.Word8Vector.fromPoly` for a (zero-cost) cast between polymorphic and monomorphic vectors.  In pure SML, you would need to use `Word8Vector.tabulate`, in which case it would make the most sense to fuse with the `Word8.fromInt o ord`.  In either case, the change will work fine with MLton 20130715  and be compatible with a future MLton release.

**Comment by achlipala** [comment]
Thanks the suggestion, @MatthewFluet.  I think I've made appropriate changes, though I've only tested with the released MLton so far.

@AlexanderAA, can you please confirm that the change I just pushed fixes the issue?

**Comment by AlexanderAA** [comment]
Confirmed, e5d78bf83c548597612f319eb9cef5a4cbacd53b fixes the issue. Thanks Adam!
