### ISSUE TITLE
"-root Meta meta" fails no effect

### ISSUE THREAD

**Issue by 1337777** [urweb/urweb#29]
1. "-root Meta meta" fails no effect on latest urweb

2. old urweb has effect,
hg clone http://hg.impredicative.com/urweb
hg checkout 4f4ae5c9243
but for example new browsers make old javascript fails in app.js here
"Uncaught TypeError: Cannot read property '_PublicId' of undefined"
case ".":
                e = {c: "c", v: v["_" + fr.f]};
                stack = stack.next;
                break;

 ¯\_ツ_/¯

**Comment by achlipala** [comment]
The poster of the issue is a known pest who sends random messages.  I can't make sense of this one, either, but I'd be happy to consider a report that actually makes sense.
