### ISSUE TITLE
How to add compiler flags

### ISSUE THREAD

**Issue by mingodad** [urweb/urweb#32]
Hello !
I'm testing urweb and I have a custom sqlite3 that I want to use and I could not find a way to tell urweb to add my custom include folder and custom library and also add custom libraries when trying compile the demo/demo.

Cheers !

**Comment by achlipala** [comment]
When you run `./configure`, it finishes by printing some variable settings.  You can override these as environment variables when running `./configure`.  Are they self-explanatory enough to help complete this exercise?  I can answer questions about any remaining necessary tweaks.

**Comment by AlexanderAA** [comment]
```
URWEB = /usr/local/bin/urweb
UWC != $(URWEB) -print-ccompiler
UWINCLUDE != $(URWEB) -print-cinclude
PGINCLUDE != pg_config --includedir
CFLAGS=-I$(UWINCLUDE) -I${PGINCLUDE}
CC="${UWC} ${CFLAGS}"

all:
	$(URWEB) -ccompiler ${CC} -dbms postgres ${DBNAME}
```
You might also be interested to check https://github.com/grwlf/urweb-monad-pack/blob/master/Makefile

**Comment by achlipala** [comment]
I will close this issue soon if there are no further updates.
