### ISSUE TITLE
On Mac OSX, `./configure` succeeds but `make` fails with `openssl.c:42:23: error: unknown type name 'CRYPTO_THREADID'`

### ISSUE THREAD

**Issue by JasonGross** [urweb/urweb#4]
[Travis says](https://travis-ci.org/JasonGross/urweb/jobs/99494499#L2529)
```
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../include/urweb  -I./../../include/urweb   -Wimplicit -Wall -Werror -Wno-format-security -Wno-deprecated-declarations -U_FORTIFY_SOURCE  -g -O2 -MT openssl.lo -MD -MP -MF .deps/openssl.Tpo -c -o openssl.lo openssl.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../include/urweb -I./../../include/urweb -Wimplicit -Wall -Werror -Wno-format-security -Wno-deprecated-declarations -U_FORTIFY_SOURCE -g -O2 -MT openssl.lo -MD -MP -MF .deps/openssl.Tpo -c openssl.c  -fno-common -DPIC -o .libs/openssl.o
openssl.c:42:23: error: unknown type name 'CRYPTO_THREADID'
static void thread_id(CRYPTO_THREADID *const result) {
                      ^
openssl.c:43:3: error: implicit declaration of function 'CRYPTO_THREADID_set_pointer' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  CRYPTO_THREADID_SET(result, pthread_self());
  ^
openssl.c:38:30: note: expanded from macro 'CRYPTO_THREADID_SET'
# define CRYPTO_THREADID_SET CRYPTO_THREADID_set_pointer
                             ^
openssl.c:74:3: error: implicit declaration of function 'CRYPTO_THREADID_set_callback' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  CRYPTO_THREADID_set_callback(thread_id);
  ^
openssl.c:74:3: note: did you mean 'CRYPTO_THREADID_set_pointer'?
openssl.c:43:3: note: 'CRYPTO_THREADID_set_pointer' declared here
  CRYPTO_THREADID_SET(result, pthread_self());
  ^
openssl.c:38:30: note: expanded from macro 'CRYPTO_THREADID_SET'
# define CRYPTO_THREADID_SET CRYPTO_THREADID_set_pointer
                             ^
3 errors generated.
make[1]: *** [openssl.lo] Error 1
make: *** [all-recursive] Error 1
```

**Comment by JasonGross** [comment]
This seems to be https://github.com/devsisters/gospdyquic/issues/1#issuecomment-102892729.  The solution is to install openssl through brew and then pass `--with-openssl=/path/to/brews/ssl-base`.  It might still be nice to get `./configure` to give a nicer error message, though.

**Comment by achlipala** [comment]
Is there any chance you can implement the fix? :-)

**Comment by achlipala** [comment]
It looks like you already did.  Thanks!

The latest issue in OS X has to do with libgmp not being found:
```
clang: error: no such file or directory: '/opt/local/lib/libgmp.a'
```

Any idea how to fix that one?  It looks like MLton's dependencies aren't being installed properly.

**Comment by vizziv** [comment]
I ran into this issue at some point. I made a symlink at `/opt/local/lib/libgmp.a` to where my `libgmp.a` lived. I just looked into this further, and I think the issue might be with MLton: it hard-codes the `/opt/local/lib/libgmp.a` in a way that fails if it doesn't exist.

**Comment by achlipala** [comment]
OK, I'm [trying to get the MLton developers to step up and fix this problem](http://article.gmane.org/gmane.comp.lang.ml.mlton.user/1664).

**Comment by JasonGross** [comment]
@vizziv what is the path to your libgmp?

@achlipala what do you want to do until they fix mlton?  (Also, another issue that prevents Travis from adopting the Linux mlton package (which would allow faster startup times of ci).)  We could say that the build should be considered as succeeding even if Mac IS fails, or we can add the relevant symlink if we can figure out what it is.

**Comment by vizziv** [comment]
My path is `/usr/local/lib/libgmp.a` (it's from brew). Furthermore, the mlton main executable is just a bash script, and you can change the relevant path (towards the end of the file) from /opt/... to this.

**Comment by JasonGross** [comment]
Thanks!  It'll be easier to make the symlink than to modify mlton by sed.

**Comment by achlipala** [comment]
@JasonGross, have you also looked at using the MLton package in [this experimental tap for Ur/Web](https://github.com/urweb/homebrew-ur), which is linked from the Ur front page?

**Comment by JasonGross** [comment]
@achlipala [that seems to work better, but it gives](https://travis-ci.org/JasonGross/urweb/jobs/99709842#L2632)
```
mlton  -mlb-path-var 'SRC /Users/travis/build/JasonGross/urweb/src' -mlb-path-var 'BUILD /Users/travis/build/JasonGross/urweb/src' -output bin/urweb src/compiler.mlb
bin/urweb -boot -noEmacs -dbms sqlite -db /tmp/urweb.db -demo /Demo demo
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test] Error 1
```

**Comment by achlipala** [comment]
*gag*  I have no idea what's going on there.  I will ask advice from @eranmeir, the maintainer of the Homebrew packages.

**Comment by JasonGross** [comment]
I also get this with the `homebrew/boneyard` tap, once I do the symlinking and pass `-Qunused-arguments`.

**Comment by achlipala** [comment]
I presume we can close this issue, now that all 4 variants build in Travis?
