### ISSUE TITLE
liburweb.so needs SONAME bump

### ISSUE THREAD

**Issue by bbarenblat** [urweb/urweb#40]
[Commit 6dad7c6](https://github.com/urweb/urweb/commit/6dad7c645d8fdb7b7237c89ff7b34e90adbb86b1) removed `memmem` from liburweb.so, so we need to bump the SONAME to indicate ABI incompatibility.

**Comment by achlipala** [comment]
Is the issue just that, hypothetically, some other code linking with this library might have used `memmem`?  In practice, it's meant to be an internal function only, and the internal calls have been changed to pick up the new name.

**Comment by bbarenblat** [comment]
Yes, that’s the issue. If it’s meant to be internal, then we should also set libtool to not export it.

**Comment by achlipala** [comment]
Do you know how to mark symbols internal, to avoid such issues in the future?

**Comment by bbarenblat** [comment]
After reexamination, I no longer think we need to do this. `memmem` was never exposed through a header file, so it’s unlikely that code linking liburweb.so depends on this particular function. We should still start using `-export-symbols` to prevent accidental leakage; I’m going to create a follow-up bug for that.
