### ISSUE TITLE
HTTP frontend should support IPv6

### ISSUE THREAD

**Issue by bbarenblat** [urweb/urweb#41]
Currently, http.c [only supports IPv4 addresses](https://github.com/urweb/urweb/blob/1a9520d6e00c63baca356d7e6aa2acc7424148bb/src/c/http.c#L361). You can trivially work around this using an IPv6-enabled reverse proxy, but native support is useful for development, and it’s easy to add.

**Comment by achlipala** [comment]
I'd love to add the prophesied easy upgrade.  Do you have a pointer to best practices?

**Comment by bbarenblat** [comment]
I’m not aware of one, unfortunately. The basic behaviour we want is this:

  - If the user does not specify `-a` to the binary, it should bind both 0.0.0.0 and :: (the IPv6 wildcard address).
  - If the user specifies `-a`, the binary should figure out whether the specified address is an IPv4 address or an IPv6 address and bind appropriately.

**Comment by mhsjlw** [comment]
Any progress on this? I'd love it as well.

**Comment by achlipala** [comment]
I know I haven't worked on it yet.  I'd love to accept a patch from someone else, though!

I might work on it in the next few months, if not.

**Comment by sielenk** [comment]
Having had a look at the code, I'm itching to give this a try...

**Comment by achlipala** [comment]
Well, I'd be very grateful if you would!  As far as I'm concerned, you now have the lock on this feature. :-)
