### ISSUE TITLE
Geographic (Map) display needed

### ISSUE THREAD

**Issue by shorero** [urweb/urweb#42]
We have a very complex web app built using a combination of web services and Ozone/EXTjs code. Ur/Web might be an alternative for us, but we absolutely need geographic (map) displays with overlays. Are there examples of Ur/Web-Geo?

**Comment by AlexanderAA** [comment]
I am not quite sure what are the exact requirements in this particular case, but it is usually easy to add any kind of visualization (graphs, maps, etc.) using Javascript FFI. Just choose any Javascript library you like and integrate into your Ur/Web application.

It is also possible to reimplement the required functionality in Ur/Web only.

https://geoip.nz might help as a simplistic example of an application which displays a map. (I have not published its source code yet. Feel free to ask questions if needed.)

**Comment by achlipala** [comment]
I like the answer from @AlexanderAA.  I'll close the issue in a few days if there are no further questions.
