### ISSUE TITLE
ccheckbox should use ‘checked’ attribute, not ‘value’

### ISSUE THREAD

**Issue by bbarenblat** [urweb/urweb#45]
`checkbox` [takes a `checked` attribute](https://github.com/urweb/urweb/blob/ae4778d/lib/ur/basis.urs#L987) to control whether or not the box is checked. `ccheckbox` [instead uses `value`](https://github.com/urweb/urweb/blob/ae4778d/lib/ur/basis.urs#L1089), which seems to be an oversight. `ccheckbox` should allow `checked` so that developers can specify the initial state of a dynamic checkbox.

**Comment by achlipala** [comment]
Hm... how about just removing `Value` without replacing it, for all of the AJAX-y input controls?  The initial value of attribute `Source` already determines the starting checked state, and presence of a different way of providing that same information could be a sign of a bug.

**Comment by bbarenblat** [comment]
Sounds fine to me.

**Comment by achlipala** [comment]
OK, done in latest commit.
