### ISSUE TITLE
urweb generates pages with XHTML doctype

### ISSUE THREAD

**Issue by bbarenblat** [urweb/urweb#50]
`urweb`-generated executables always generate pages with an XHTML doctype, which causes browsers to fall back to XHTML quirks mode. This in turn forces developers to target the now-ancient XHTML DOM when writing their CSS and JavaScript.

`urweb` already supports many HTML 5 tags; switching to an HTML 5 doctype is a logical next step. If backward compatibility with ancient browsers is truly necessary, then `urweb` should switch to the HTML 5 doctype by default and allow programmers to override its selection in their .urp files.

**Comment by achlipala** [comment]
Are you aware of the `html5` .urp option?  It seems like you might just be asking to invert the default behavior.

**Comment by bbarenblat** [comment]
I was not aware of the `html5` option! That’s exactly what I wanted. How would you feel about making it the default?

Orthogonally, the documentation could be a bit clearer as to what `html5` actually does – would you accept a PR to note in the manual that `html5` changes the doctype?

**Comment by achlipala** [comment]
I've switched it to the default, added an `xhtml` option to get the old behavior, and updated the manual along the lines you suggested.
