### ISSUE TITLE
FastCGI backend ignores request IDs

### ISSUE THREAD

**Issue by bbarenblat** [urweb/urweb#57]
`urweb` currently generates FastCGI binaries which always return request IDs equal to 0, which causes FastCGI failures on nginx.

The [FastCGI specification](https://htmlpreview.github.io/?https://github.com/FastCGI-Archives/fcgi2/blob/master/doc/fcgi-spec.html) allows for multiplexed requests to FastCGI applications. Each request is identified by a reusable request ID while in flight ([§3.3](https://htmlpreview.github.io/?https://github.com/FastCGI-Archives/fcgi2/blob/master/doc/fcgi-spec.html#S3.3)). In practice, neither nginx nor lighttpd multiplexes (see [ngx_http_fastcgi_module.c](http://hg.nginx.org/nginx/file/release-1.10.1/src/http/modules/ngx_http_fastcgi_module.c) and [mod_fastcgi.c](https://redmine.lighttpd.net/projects/lighttpd/repository/revisions/lighttpd-1.4.39/entry/src/mod_fastcgi.c#L2888)); each simply always uses request ID 1. Lighttpd doesn’t even bother to check the request IDs on responses; however, nginx [verifies that the request ID is 1](http://hg.nginx.org/nginx/file/release-1.10.1/src/http/modules/ngx_http_fastcgi_module.c#l2591), and because `urweb`-generated FastCGI binaries [always use request ID 0](https://github.com/urweb/urweb/blob/d64871d978719a36f3f52d6fdaef80fc757fa752/src/c/fastcgi.c#L73), nginx refuses to interact with them.

We can hack around this by always using request ID 1 instead of request ID 0, which is a one-line patch. However, the standard-compliant way to handle this is to save the request ID when we start processing a request and associate the request ID with our response. (FastCGI applications do not have to support multiplexing to be standard-compliant.) This wouldn’t be much harder to implement (probably under five lines), so I’d prefer that approach instead.

**Comment by bbarenblat** [comment]
Well, it was a bit more than five lines, but it wasn’t too bad. @achlipala, how does this look?

**Comment by achlipala** [comment]
Sorry for the delay, but I can say now: LGTM!
