### ISSUE TITLE
Some dynamically updated style properties are dropped during updates

### ISSUE THREAD

**Issue by bbarenblat** [urweb/urweb#58]
When dynamically generating styles, updates to certain properties cause the property to become unset in the DOM. For example, consider this simple program, where clicking the mouse should cause text to move:

```urweb
val main : transaction page =
    xPosition <- source 0;
    return <xml>
      <body
          style="height: 400px;"
          onclick={fn click => set xPosition click.ClientX}>
        <div dynStyle={
            currentX <- signal xPosition;
            return (oneProperty (STYLE "position: absolute;")
                                (value (property "left") (atom (show currentX))))
        }>some text</div>
      </body>
    </xml>
```

The expected behaviour here is for the words ‘some text’ to change x-coordinate to match your mouse click. However, they don’t – they remain at the left of the screen. Inspecting the DOM with Chrome shows that the `left` parameter disappears from the style settings on click.

This seems to happen for some, but not all styles. `left`, `right`, `top`, and `bottom` all disappear. On the other hand, this example works perfectly for `x`, `y`, and `z-index`, though there’s no visible effect.

You can also observe this behaviour without interaction using this program, which just increments the relevant property at a rate of 20&nbsp;Hz:

```urweb
val main : transaction page =
    xPosition <- source 0;
    let
        fun incrementer () =
            x <- get xPosition;
            set xPosition (x + 1);
            sleep 50;
            incrementer ()
    in
        return <xml>
          <body onload={spawn (incrementer ())}>
            <div dynStyle={
                currentX <- signal xPosition;
                return (oneProperty (STYLE "position: absolute;")
                                    (value (property "left") (atom (show currentX))))
            }>some text</div>
          </body>
        </xml>
    end
```

**Comment by achlipala** [comment]
Well, that was something of a wild goose chase, figuring out what's going on here. :)

Yet again using lax static typing exposes the programmer to aggravation!  The problem was just that, while `0` is a valid CSS property value for a position, `1` or another number isn't.  The latter needs a unit.  So, appending `"px"` to the property value fixes everything.

In other words, Ur/Web was passing along exactly the CSS text you requested, but the browser was ignoring "ill-typed" property values.
