### ISSUE TITLE
Ur/Web <form id={x}>..</form> tag resolves in HTML form tag without "id" attribute

### ISSUE THREAD

**Issue by grwlf** [urweb/urweb#61]
Here is the exact code which triggers the bug

```
  fid <- fresh;
  return <xml>
          <form id={fid} class="form-group">
            <upload{#File}/>
            <submit id={fid} style="visibility:hidden" action={receiveFile}/>
          </form>
  </xml>
```

**Comment by grwlf** [comment]
Just noted that {fid} is duplicated in both form and submit tag. This was my attempt to investigate situation. Removing {fid} from submit doesn't change the situation. Here is the resulting HTML:
```
 <form method="post" action="/App2/receiveFile" enctype="multipart/form-data" class="form-group"><input type="hidden" name="Sig" value="3861A91B9F9CDA598EB12C14899ADB707168F87BE0DE9EA6782A9CD7E62D2929" />
<input type="file" name="File" />
<input type="submit" style="visibility: hidden;" id="uw0" />
</form>
```

**Comment by grwlf** [comment]
I am using urweb-20161022

**Comment by bbarenblat** [comment]
I can reproduce this on Debian’s 20161022.

**Comment by achlipala** [comment]
Should be fixed now!  `<form>` is treated specially, not using the compiler code for processing other tags, but I just added a special case there for `id`.

**Comment by achlipala** [comment]
I need to fix the tests to take this change into account.
