### ISSUE TITLE
dynClass attribute suppresses static classes

### ISSUE THREAD

**Issue by grwlf** [urweb/urweb#64]
The code below produces `span` element with both `class` and `dynClass` attributes. I assumed urweb to merge them into one single `class` attribute. Unfortunately, it is not the case: the code below produced `<span class="glyphicon-star"/>` (or glyphicon-star-empty, depending on the value of `sfav` signal). class="glyphicon" was lost.

```
346             <td>
347               <button class="btn btn-default" onclick={fn _=>
348                 f <- rpc(toggleFavorites u r.F.Nam i.Id);
349                 (case f of     
350                   |True => set sfav (CLASS "glyphicon-star")
351                   |False => set sfav (CLASS "glyphicon-star-empty")); 
352                 return {}      
353               }>               
354                 <span class="glyphicon" dynClass={ signal sfav }/>
355               </button>        
356             </td>  
```

I'm on urweb  20161022

**Comment by achlipala** [comment]
I'm not surprised by this behavior, so maybe the solution is just to document it.  Is there a strong reason to change the behavior?

**Comment by grwlf** [comment]
Well, in Bootstrap multiple classes is often the case. Probably, other people will try to do the same thing. I suggest adding a compile warning at least.

**Comment by achlipala** [comment]
It's easy to include as many classes as you want with `dynClass` alone, even if some of them are effectively static.

**Comment by AlexanderAA** [comment]
I had produced several bugs because of this. 

If it is still being discussed, I vote for compiler error or, better, fix to join class and dynClass classes.
The latter option is better because it would make CSS class descriptions clear and concise (to me at least).

@grwlf Do you have a patch for this?

**Comment by achlipala** [comment]
OK, I'm convinced to implement the auto-combining semantics at some point in the next few months!

**Comment by AlexanderAA** [comment]
Is there anything besides urweb.js and, maybe, monoize.sml, which will need to be changed?
There is also `dynStyle` attribute which probably has to have the same behaviour.

Commits I am looking at:
85341a176564ac3ce4e0a4ec4612262e2945660a
e1ea17cb21e3193a99cfd93d7e264ba0176f66f5
4906733e1c12fd167a4236c63201a8f4e6daad63

**Comment by grwlf** [comment]
@AlexanderAA no, unfortunately, I dont have a patch.

> OK, I'm convinced to implement the auto-combining semantics at some point in the next few months!

Thanks! I'm looking forward into testing it.

**Comment by achlipala** [comment]
I think you pinpointed the right affected files (with `monoize.sml` definitely included).  The JavaScript functions behind these operations should change to take static data as additional arguments, to be merged in at every update.
