### ISSUE TITLE
sqlite backend: sql generation error?

### ISSUE THREAD

**Issue by fabriceleal** [urweb/urweb#67]
I get a sql error when trying to add a tree node in the page http://localhost:8080/Demo/Tree/main of the demo application (http://www.impredicative.com/ur/demo/) with a sqlite3 backend

_Fatal error: Error preparing statement: near "DISTINCT": syntax error
SELECT T_Tab.uw_Id, T_Tab.uw_Nam, T_Tab.uw_Parent FROM uw_Tree_t AS T_Tab WHERE ((T_Tab.uw_parent IS NOT DISTINCT FROM 1))_

**Comment by achlipala** [comment]
OK, so `IS NOT DISTINCT FROM` must be a Postgres-ism.  Do you know the right way to accomplish the same effect in SQLite?

**Comment by fabriceleal** [comment]
from what i'm reading, `a IS NOT DISTINCT FROM b` seems to be equivalent to `a = b OR (a is NULL AND b is NULL)` in sqlite

**Comment by achlipala** [comment]
And how would you feel about trying to implement a patch yourself? :)

I would get to it eventually, but probably in at least a few weeks from now.

**Comment by fabriceleal** [comment]
I wouldn't mind so much, but i can't promise anything! :) I was already greping through the source to locate the sql-generation code.

**Comment by ashalkhakov** [comment]
Hmmm is this not the same issue? :) Please see my [PR](https://github.com/urweb/urweb/pull/71).

**Comment by fabriceleal** [comment]
i think it is

**Comment by achlipala** [comment]
OK, then @ashalkhakov already addressed the issue.
