### ISSUE TITLE
Better error message for multiple blank lines in *.urp file.

### ISSUE THREAD

**Issue by Izacht13** [urweb/urweb#70]
As the title requests, an error message showing erroneous line feeds in the project file would be very helpful, especially in a case like mine (*Being new to both ML languages and Ur/Web*) where I hadn't known that the lexer/parser uses the linefeed to denote separation.

**Comment by bbarenblat** [comment]
For reference, trying to compile the file

    database dbname=somedb
    sql somesql.sql

    rewrite url Main/main
    rewrite all Main/*
 
    main

produces

    Missing source file: /tmp/rewriteurlMain/main.ur
    Filename doesn't start with letter: *
    Missing source file: /tmp/rewriteallMain/*.ur
    Missing source file: /tmp/main.ur

**Comment by ashalkhakov** [comment]
How about adding a new feature: JSON or XML syntax for urp files? So that we could write some tools for preprocessing it? Off the top of my head: adding "library" directives via a tool (say `urweb-npm install mypackage` that calls out to `npm install`, and then adds an entry to the urp file).

Is there a syntax definition for urp files anywhere?

**Comment by achlipala** [comment]
Personally, I'd be strongly against making JSON or XML the only format available for project files.  I find the current syntax much more pleasant to read and write.  The configuration language is also designed to support modular assembly out of multiple files, some of which may be generated automatically.

**Comment by achlipala** [comment]
But I do agree that it makes sense to tweak the parsing error messages, and I accept this to-do item for some indeterminate future time.

**Comment by achlipala** [comment]
OK, fixed with my latest commit.
