### ISSUE TITLE
Emacs not found errors

### ISSUE THREAD

**Issue by tobia** [urweb/urweb#83]
Hello. I just installed the `urweb` package from Ubuntu Xenial, got the demo files from this repo, and compiled them, as shown in the tutorial:

    urweb -dbms sqlite -db demo/db.sqlite -demo /Demo demo

It works and gives me a working executable, but my terminal is spammed with 174 errors about Emacs not being found:

	>>> emacs --eval "(progn (global-font-lock-mode t) (add-to-list 'load-path \"/usr/share/emacs/site-lisp/urweb-mode/\") (load \"urweb-mode-startup\") (urweb-mode) (find-file \"demo/alert.ur\") (switch-to-buffer (htmlize-buffer)) (write-file \"/home/tobia/urweb/demo/out/alert.ur.html\") (kill-emacs))"
	sh: 1: emacs: not found
	>>> emacs --eval "(progn (global-font-lock-mode t) (add-to-list 'load-path \"/usr/share/emacs/site-lisp/urweb-mode/\") (load \"urweb-mode-startup\") (urweb-mode) (find-file \"demo/alert.urs\") (switch-to-buffer (htmlize-buffer)) (write-file \"/home/tobia/urweb/demo/out/alert.urs.html\") (kill-emacs))"
	sh: 1: emacs: not found
	>>> emacs --eval "(progn (global-font-lock-mode t) (add-to-list 'load-path \"/usr/share/emacs/site-lisp/urweb-mode/\") (load \"urweb-mode-startup\") (urweb-mode) (find-file \"demo/batch.ur\") (switch-to-buffer (htmlize-buffer)) (write-file \"/home/tobia/urweb/demo/out/batch.ur.html\") (kill-emacs))"
	sh: 1: emacs: not found
	...

I never installed or used Emacs on this computer and I made sure not to install the optional `urweb-mode` package. So why is the compiler expecting to find an `emacs` executable? Is this a bug in the Debian / Ubuntu package? Is it a specific dependency of the Demo application?

**Comment by achlipala** [comment]
That's how the `-demo` flag is meant to behave, but you can cancel the behavior with `-noEmacs`.  Somehow I was thinking the demo index page included `-noEmacs` in its example command line, but I see that it doesn't.  I will add it.

**Comment by tobia** [comment]
Oh right, it's for syntax highlighting the demo listings. Sorry, I got somewhat confused by the error messages.

**Comment by achlipala** [comment]
OK, I made the change in the repo.  It will go up on the web site with the next release.
