### ISSUE TITLE
Extension proposal: Exposing Js' <script/> tag

### ISSUE THREAD

**Issue by sheganinans** [urweb/urweb#85]
Say I want to add a visitor counter to my website: https://www.revolvermaps.com/

Right now this means I now have to write my own custom C ffi code to generate the proper xbody tag from a string, or use some existing solution like Uru3 https://github.com/grwlf/uru3/blob/master/Uru/Script.c (Thanks @grwlf !)

How about we add a new tag in Basis: `jsscript `

From the Revolver Maps example, you would have something like this:

```html
<jsscript type="text/javascript" src="http://rf.revolvermaps.com/..." />
```

**Comment by achlipala** [comment]
I consider it a feature, not a bug, of the Ur/Web compiler to _guarantee_ that no values of the Ur/Web HTML type contain inclusions of JavaScript files (with the FFI voiding guarantees, as usual).  The security implications would be very hard to bound.  But have you seen the `script` directive for `.urp` files?

**Comment by sheganinans** [comment]
That makes perfect sense. A new tag definitely seems like the wrong approach.

Since in this particular case the HTML they provide is a self-modifying `script` element, it is possible to attach a `script` element to the DOM with the correct parameters with the site allowed in the `.urp` file. The only question now is, what would be the best way to do it? 

My guess is the best way would be to make a lib that uses the `file` and `script` directives to read in and include some glue code into the lib, the glue code is then exposed by the lib with `jsFunc`, then imported into my main project with the `library` directive.

JS:

```js
Vis_map = {
    gen_vis_map: id => {
        var s = document.createElement("script");
        s.type = "text/javascript";
        s.src = "http://rf.revolvermaps.com/...";
        s.async = "async";
        document.getElementById(id).append(s); }}
```

Main file:

```urweb
fun main () =
    vis_map_id <- fresh;
    return <xml>
        (*stuff*)
        <div id={vis_map_id}>
        {Vis_map.gen_vis_map vis_map_id}
    </xml>
```

I guess this can be extended to support any type of self modifying script, just pass in the appropriate `s.src` url and rename everything to be more general. My question is then, does this usage of the `script` and `library` directive void the guarantees of the compiler as well? Since we are now able to inject arbitrary `<script/>` elements into the DOM given we have the `id`.

**Comment by achlipala** [comment]
Yes, that seems like a good approach.  I assume you would plan to put the Ur/Web code into a library module with nice encapsulation, so that client code doesn't need to know that an ID has been allocated.  You can even use the Ur/Web `<active>` tag to embed the ID allocation directly within an HTML fragment, supporting a simpler API exported from the module.

**Comment by sheganinans** [comment]
Right! Thanks for those tips, I'll implement it as a function that takes a url piece and returns an `active` tag with the full url constructed internally.
