### ISSUE TITLE
Installation instructions in readme

### ISSUE THREAD

**Issue by hkasera** [urweb/urweb#86]
Hello,

I believe it would be great to have installation instructions of Ur/Web in the readme file. I found this [link](http://www.impredicative.com/pipermail/ur/2015-October/002235.html) which mentions the installation instructions. It would be great to have the same in readme file.

If it is alright I would like to send a PR adding the same. Let me know if I should go ahead and do this!

Regards,
Harshita Kasera

**Comment by achlipala** [comment]
Those instructions are only for Mac OS, but I could imagine trying to include the easiest instructions for each common platform.  Is that your suggestion?

**Comment by hkasera** [comment]
Yes exactly! I feel it would be easier if they were in Readme file rather than searching the same on the internet.

**Comment by achlipala** [comment]
OK, that's a good idea, and I think it's best for me to add instructions on popular package systems myself.  Consider it enqueued in my to-do list!

**Comment by hkasera** [comment]
That's great! Thank you for acknowledging this. I hope to see the update soon.
