### ISSUE TITLE
urp file directive not honored

### ISSUE THREAD

**Issue by monga** [urweb/urweb#88]
According to the manual the `file` directive should:

> `file URI FILENAME` asks for the application executable to respond to requests for `URI` by serving a
snapshot of the contents of `FILENAME` as of compile time. That is, the file contents are baked into the
executable.

I have this `.urp` file:

```
rewrite url Bug/main
file https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Circle-empty-512px.svg/514px-Circle-empty-512px.svg.png circle.png

bug
```

The original image is just a **black** ![circle](https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Circle-empty-512px.svg/514px-Circle-empty-512px.svg.png)

The local file ![circle.png](https://user-images.githubusercontent.com/1064026/30921130-045a9ede-a3a6-11e7-8acc-b88e6c1aa6b5.png) is instead **red** circle.

I expect that this app would show the red one, not the original black circle.

```
fun main (): transaction page = return <xml>
  <head>
    <title>Hello world!</title>
  </head>

  <body>
    <h1>Hello world!</h1>
    <p><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Circle-empty-512px.svg/514px-Circle-empty-512px.svg.png"/></p>
  </body>
</xml>
```

Instead, the black one is loaded, indeed with a remote http GET. The contents *backed into the app* are not used.

Am I misunderstanding the manual? I believe in the generated html the url should not be the original one, but a reference to the *embedded* resource.

**Comment by achlipala** [comment]
Ah, it seems you expected `file` to control resolution of URLs that appear in generated HTML pages.  Instead, `file` controls responses to HTTP requests received by your application itself.  Does that clear it up?

**Comment by monga** [comment]
Yes, you are right. Now it is clear. Only requests to the app are translated.
