### ISSUE TITLE
scalability

### ISSUE THREAD

**Issue by fullreset** [urweb/urweb#91]
From the GitHub FAQ, a solution proposed for scalability:

> "However you can split ur projects into pieces keeping compilation time low - so this may not be a real issue."

This helps with compile times; however scalability of a service in terms of users etc remains a problem since there's no socket, RPC or other means for UR instances to communicate with each other. If one compilation unit is in charge of authentication, and another needs to verify that the user is logged in, the only solution is to use the (unsafe) FFI route, or to depend entirely on the database backend.

This seems like a rather serious shortcoming ...

**Comment by achlipala** [comment]
I don't remember seeing that question/answer added (I haven't been watching the wiki carefully), and I don't endorse it as "best practices."

**Comment by fullreset** [comment]
My point, really, was not just that the FAQ was misleading, but that perhaps Ur/Web should have some sort of mechanism to allow communication between instances. When a project hits X users, or needs Y servers or data centers, a single running instance is not enough ...

That said, thanks for Ur, and thanks for your rapid reply!

**Comment by achlipala** [comment]
Yes, support for largely automatic scaling with distributed systems would be neat.  However, I think it's very rare for real applications to require multiple servers, beyond master-backup strategies for fault tolerance.  Ur/Web apps are so speedy and resource-light that 32-core servers should be sufficient for almost all cases!

Feel free to open a feature request for some kind of automatic distribution, but I, at least, wouldn't plan to tackle it soon.
