### ISSUE TITLE
How to build and run demo on MacOS

### ISSUE THREAD

**Issue by nitinsurana** [urweb/urweb#92]
## Installing Urweb Source

* Downloaded 2017 source-code
* Fixed openssl issue by executing the following commands :
  - brew uninstall --ignore-dependencies openssl
  - brew install openssl
  - export CPPFLAGS="-I/usr/local/opt/openssl/include"
  - export LDFLAGS="-L/usr/local/opt/openssl/lib"
* ./configure
* make
* sudo make install
* Ignore the error about ldconfig
* remove `-ldconfig` from Makefile
* ran `sudo make install` again and ignored some other issue, because the bin/ had urweb executable created.
 
## Running Demo
* `bin/urweb -dbms sqlite -db random.sqlite -demo /Demo demo`
* But then it opens up lisp emacs editor within terminal having a message at the bottom similar to "Cannot open/load htmlize"
* On closing the editor using `ctrl+z` there's this :
```
>>> emacs -no-init-file --eval "(progn (global-font-lock-mode t) (add-to-list 'load-path \"/usr/local/share/emacs/site-lisp/urweb-mode/\") (load \"urweb-mode-startup\") (load \"htmlize\") (urweb-mode) (find-file \"./alert.ur\") (switch-to-buffer (htmlize-buffer)) (write-file \"/Users/coding_idiot/Documents/urweb-20170720/demo/out/alert.ur.html\") (kill-emacs))"
```
I'm practically stuck here. Any help would be really appreciated.

Thanks

References :
https://github.com/vysheng/tg/issues/811

**Comment by nitinsurana** [comment]
I also tried `brew install urweb` and tried to run the demo using this urweb executable but it gives the same error `cannot open/load file htmlize`.

**Comment by hkasera** [comment]
May be you should -noEmacs option.

bin/urweb -dbms sqlite -db random.sqlite -demo /Demo demo -noEmacs

Ref - https://github.com/urweb/urweb/issues/83
"_That's how the -demo flag is meant to behave, but you can cancel the behavior with -noEmacs. Somehow I was thinking the demo index page included -noEmacs in its example command line, but I see that it doesn't. I will add it_."

**Comment by achlipala** [comment]
Yes, the suggested fix is correct.  The demo instructions already have that change in the working version.  They'll be published on the project site with the next release.

**Comment by nitinsurana** [comment]
@hkasera  works like a charm, thanks!
