### ISSUE TITLE
Error while making rpc call

### ISSUE THREAD

**Issue by hkasera** [urweb/urweb#94]
Hello,

I am receiving this below error while making a rpc call - 
_Server-side code uses client-side-only identifier "Basis.mouseEvent"_

Basically I am reading values from database and listing into a table. In each table row, there is a button which will make a rpc call with parameter as one of column value returned from the database.

```
rows <- queryX (SELECT * FROM peers WHERE)
		            (fn row => <xml><tr>
		            	<td>{[row.Peers.C]}</td>
		             	<td>
		            		<button value="Update" onclick={fn _ => n <- rpc (increment row.Peers.C); set src n}/>
		             	</td>
		            </tr></xml>);
```
row.Peers.C is a string column.

I am unable to comprehend the error. Any insights into this would be helpful.

**Comment by achlipala** [comment]
Can you share a self-contained example, ideally in a single `.ur` file, so I can try compiling?

**Comment by hkasera** [comment]
Here it is -
https://gist.github.com/hkasera/5d2005368e385cf2c95b200aa71b6fbd

**Comment by hkasera** [comment]
Can I please get an update on this?

**Comment by achlipala-biz** [comment]
Sorry, I'm busy and can't promise when I'll look into it.

**Comment by hkasera** [comment]
Hello,

We got a  reply on the mailing list that -

> Changing the `onclick` handler to avoid capturing
> `row.Peers.A` - i.e., I changed your `SELECT` statement to
> 
>     SELECT Peers.C FROM peers WHERE peers.A > {[me]} OR peers.A < {[me]}
> 
> and it compiled.
> 
> This is definitely a case of a bad error message, but there may be more
> in play here. It sounds like the compiler is trying to evaluate the body
> of the `onclick` handler on the server instead of on the client, which
> seems wrong to me. This may also be related to Ur/Web's apparent
> inability to handle client IDs on the client side [1]. In any case,
> though, if anybody else has experienced issues like this, please speak
> up.

It would be great when you have time, to help us understand this.

Regards,
Harshita Kasera

**Comment by achlipala** [comment]
I think Benjamin's diagnosis on the mailing list is pretty good.  I'll follow up there now.
