### ISSUE TITLE
Can’t get client ID on the client

### ISSUE THREAD

**Issue by bbarenblat** [urweb/urweb#96]
Attempting to compile

```urweb
val f : transaction page =
    return <xml><body>
      <active code={s <- self; return <xml></xml>} />
    </body></xml>
```

(with the appropriate `safeGet` incantation in the .urp file) produces the error “Unsupported FFI function Basis.self in JavaScript”. This conflicts with section 8.6.5 of the reference manual, which states that “These IDs may be retrieved both on the client and on the server, during execution of code related to a client.” Is `self` supposed to be supported client-side?

**Comment by achlipala** [comment]
That's a bug in the manual.  It's fixed now, for the next release, etc.
