### ISSUE TITLE
How to check for undefined value returned from javascript ffi

### ISSUE THREAD

**Issue by nitinsurana** [urweb/urweb#97]
```
fun myloop v =
        sleep 1000;
        x <- JsWebrtcJs.getDatastore "key";
        if x = "undefined" then
            myloop v
        else
            return x
```

getDatastore returns undefined (javascript). Instead of looping the function returns. 
How to check for undefined javascript function return in urweb and the make the above function loop until the value is available ?

Also, went through the [manual](http://www.impredicative.com/ur/manual.pdf) but can't find the replacement for console.log, it is possible to log in the console instead of alert ?

**Comment by achlipala** [comment]
I consider it a feature, not a bug, that Ur/Web doesn't have a concept of "undefined."  My suggestion: wrap the JavaScript function (in JavaScript) so that it never returns `undefined`.

Also, the Ur/Web `debug` function acts as `console.log`, when run in a browser.
